// ╔══════════════════════════════════════════════════════════════════╗
// ║   ELF&DÉMON : ÉTERNAL WAR — SERVEUR DE JEU NODE.JS             ║
// ║   Protocole TCP custom (my9yu / DragonPals AS3)                 ║
// ║   1833 opcodes extraits automatiquement des fichiers AS3        ║
// ║                                                                  ║
// ║   Installation:                                                  ║
// ║     npm install                                                  ║
// ║     node game_server.js                                         ║
// ║                                                                  ║
// ║   Variables d'environnement:                                     ║
// ║     GAME_PORT=8888                                               ║
// ║     SUPABASE_URL=https://xxx.supabase.co                        ║
// ║     SUPABASE_KEY=votre_service_role_key                         ║
// ╚══════════════════════════════════════════════════════════════════╝

'use strict';
const net = require('net');
const { createClient } = require('@supabase/supabase-js');

// ─── CONFIG ───────────────────────────────────────────────────────────────────
const PORT       = parseInt(process.env.GAME_PORT   || '8888');
const SUPA_URL   = process.env.SUPABASE_URL         || 'https://fgzulqopyxtfmtlfctxx.supabase.co';
const SUPA_KEY   = process.env.SUPABASE_KEY         || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnenVscW9weXh0Zm10bGZjdHh4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTU0ODU5NiwiZXhwIjoyMDk1MTI0NTk2fQ.BktjHUD8h7qQbgsijevHrym5ogO5nmtaEBuosGPiRyE';
const supabase   = createClient(SUPA_URL, SUPA_KEY);

const OPCODES = {
  ActWishCmd: {
    ENTER_VOW: 1,
    VOW: 2,
    EXCHANGE: 3,
    PUSH_AWARDVOS: 4,
  },
  ActivityRankCmd: {
    ACTIVITY_RANK: 1,
    QUERY_USER_RANK: 2,
    HAVE_REWARD_STATE: 3,
  },
  AlchemyCmd: {
    GETUSERALCHEMY: 1,
    PRACTICE: 2,
    PRACTICE_TO_FRIEND: 3,
    FAST_PRACTICE: 4,
  },
  AllianceCmd: {
    QUERY_ALLIANCE_VIEW: 1,
    QEURY_MY_ALLIANCE_VIEW: 2,
    LIST_ALLIANCE_BUILDING: 3,
    LIST_ALLIANCE_BAG: 4,
    LIST_ALLIANCE_SKILL: 5,
    LIST_MY_ALLIANCE_SKILL: 6,
    LIST_TOTAY_DONATE: 7,
    PAGE_ALLIANCE_LIST: 8,
    DONATE: 9,
    APPLY_ALLIANCE: 10,
    CANCEL_APPLY_ALLIANCE: 11,
    INVITE_ALLIANCE: 12,
    ANSWER_INVITE: 13,
    ANSWER_APPLAY: 14,
    KICK_MEMBER: 15,
    LEFT_ALLIANCE: 16,
    CREATE_ALLIANCE: 17,
    CHANGE_POS: 18,
    APPLY_CHAIRMAN: 19,
    UPGRADE_BUILDING: 21,
    UPGRADE_MY_ALLIANCE_SKILL: 22,
    UPGRADE_ALLIANCE: 23,
    STORE_BAG: 24,
    FETCH_BAG: 25,
    UPDATE_DECLARATION: 26,
    LIST_APPLY: 27,
    BUY_ITEM: 28,
    QUERY_MY_ALLIANCE: 29,
    SWITCH_POS: 30,
    UPGRADE_ALLIANCE_SKILL: 31,
    COOL_UPGRADE: 32,
    QUERY_ALLIANCE_MEMBER: 33,
    COOL_JOIN: 34,
    QUERY_ALLIANCE_BY_NAME: 35,
    QUERY_UNFULE_ALLIANCE_LIST: 36,
    RAPID_INVITE: 37,
    REFUSE_ALL_APPLY: 38,
    UNFREEZE: 39,
    UPDATE_DECLARE: 40,
    RANDOM_ALLIANCE: 41,
    USE_CONTRIBUTE_ITEM: 42,
    USE_SPEED_ITEM: 43,
    RENAME: 44,
    ALLIANCE_DRAW_FLOURISHING_REWARD: 50,
    PUSH_ALLIANCE: 1001,
    PUSH_INVITE: 1002,
    PUSH_APPLY: 1003,
    PUSH_KICKED: 1004,
    PUSH_ANNOUNCE: 1005,
    PUSH_DECLARE: 1006,
    PUSH_CREATE_NEW_HAND_ALLIANCE: 1007,
  },
  AllianceFubenCmd: {
    ENTER_VIEW: 1,
    CHALLENGE: 2,
  },
  AllianceHallCmd: {
    GET_ALLIANCE_HALL_STATUS: 1,
    ENTER_HALL: 2,
    LEFT_HALL: 3,
    CHARGE_GODDESS: 4,
    COLLECT_START: 5,
    COLLECT_FINISHED: 6,
    USER_MOVE: 7,
    EXPR_DOUBLE: 8,
    SET_AUTO_JOIN_AND_DOUBLE_EXP: 9,
    PUSH_ALLIANCE_HALL_STATUS: 1001,
    PUSH_USER_CHANGES: 1002,
    PUSH_GODDESS_CHARGE: 1003,
    PUSH_NEW_GOODS: 1004,
    PUSH_EXPR_PROFIT: 1005,
    PUSH_COLLECT_STATUS: 1006,
    PUSH_USER_MOVE: 1007,
  },
  AnswerForXtrasCmd: {
    ANTI_PUSH_QUESTION: 1,
    ANTI_ANSWER: 2,
    ANTI_PUSH_FREEZE: 3,
    CHECK_STATUS: 4,
  },
  ArenaCmd: {
    ARENA_LUCK_RANK_GRABED_WIN: -10089,
    ARENA_LUCK_RANK_NOTE_GRABED: -10088,
    ARENA_LUCK_RANK_ALL_UPDATA: -10087,
    ARENA_FIGHT_OVER: -10086,
    QUERY_ARENA_VIEW: 1,
    QUERY_OPPOSE_LIST: 2,
    ATTACK: 3,
    COOL_ATTACK_TIME: 4,
    BUY_ATTACK: 5,
    VIEW_FIGHT: 6,
    EXCHANGE_SCORES: 7,
    FETCH_RANK_LIST: 8,
    REWARD_DAILY: 9,
    QUERY_DAILY_REWARD: 10,
    EXCHANGE_BUYS: 11,
    QUEREY_MY_RANK: 12,
    QUERY_LUCKY_RANK: 13,
    PUSH_ATTACKED: 1001,
    PUSH_DAILY_REWARD: 1002,
    PUSH_LUCKY_RANKS: 1003,
  },
  ArtifactEquipGiftCmd: {
    GET_MY_INFO: 1,
    BUY_GIFT: 2,
  },
  AsterismFubenCmd: {
    ENTER_AREA: 1,
    ATTACK_MONSTER: 2,
    BACK_HOME: 4,
    QUERY_ASTERISM_FUBEN: 5,
    BUT_ATTACK_COUNT: 6,
    REVIVE: 7,
    BATTLE_OVER: 79001,
  },
  AwardRoomCmd: {
    QUERY_DAILY_INFO_ACTION: 2401,
    SIGN_IN: 2402,
    REWARD_GUIDE: 2403,
    REWARD_SIGN: 2404,
    RE_SIGN_IN: 2405,
    RETRIEVEEXP_INFO: 4302,
    RETRIEVEEXP_RETRIEVE: 4303,
  },
  BalanceCmd: {
    USER_BUY_COIN: 108,
    TX_BUY_ENERGY: 109,
    USER_BUY_PACK: 111,
    GIFT_BUY_COST_GIFT: 209,
    TX_GIFT_SIGN_IN: 215,
    TX_BLESS: 411,
    TX_BLESS_ABILITY: 415,
    TX_COMBINE_ITEM: 604,
    TX_OPEN_ITEM_BOX: 605,
    BUY_PEARL_CELLS: 702,
    PET_CLEAR_COOL_TIME: 703,
    TX_BUY_DRAGON_SOUL: 729,
    TX_PET_PEARL_CONVERT: 733,
    USEREQUIP_FORGE: 803,
    USEREQUIP_SHOW: 809,
    NPC_SHOP_BUY_ITEM: 1001,
    TX_MALL_SEND_ITEM: 1005,
    ARENA_COOL_ATTACK: 1304,
    ARENA_BUY_ATTACK: 1305,
    FINISH_HOOK: 1406,
    TX_TRAIN_MAGIC_WING: 1507,
    TX_RESET_MAGIC_WING_ATTR: 1509,
    DIVINE: 1902,
    FINISH_DIVINE_TASK: 1904,
    BUY_DIVINE_TIME: 1910,
    ALLIANCE_DONATE: 2009,
    CREATE_ALLIANCE: 2017,
    ALLIANCE_COOL_UPGRADE: 2032,
    ALLIANCE_COOL_JOIN: 2034,
    DEVILDOM_REVIVE_RIGHT_NOW: 2107,
    DEVILDOM_ATTACK_RIGHT_NOW: 2109,
    DEVILDOM_ENHANCE_FIGHT_ATTR: 2114,
    TX_DAILY_ACTIVE_RE_SIGN_IN: 2405,
    TOWER_REVIVE: 2906,
    MARKET_BUY: 3205,
    TX_BLUE_LOTTERY_BUY_COUNT: 3407,
    TX_FARM_SPEED_UP: 4209,
    TX_RETRIEVEEXP_RETRIEVE: 4303,
    TX_BUY_SLAVE_RANSOM: 4605,
    TX_BUY_SLAVE_SAVE_TIMES: 4608,
    TX_BUY_SLAVE_CAPTURE_TIMES: 4611,
    TX_BUY_SLAVE_CLEAR_CD_TIME: 4619,
    TX_FEAST_REVIVE_RIGHT_NOW: 4704,
    TX_FEAST_BUY_CD: 4712,
    TX_ENTER_HALL: 4802,
    TX_ALLIANCE_HALL_EXPR_DOUBLE: 4808,
    TX_BUY_CLOTHES_RENEWAL: 5007,
    TX_SEAL_RESET: 5304,
    TX_BUY_CLOBER: 5502,
    TX_EXCHANGE: 5504,
    REWARD_GOLD_COUPON_GIFT: 5703,
    TX_VOW_VOW: 5802,
    TX_PRANK_BUY_KEY: 5906,
    TX_GROUP_ORDER: 6102,
    TX_GROUP_PAY: 6103,
    BUY_FUND: 6201,
    SEND_FUND: 6204,
    BUY_PLAN: 6401,
    BUY_WEEK_MONEY_PLAN: 7101,
    TX_POTENTIAL_UPSTAR: 7122,
    DRAW_HERO_CARD: 7206,
    TX_GODOTS_BUY_PACK: 7209,
    TX_GODOTS_CLEAR_CD: 7212,
    TX_EXCHANGE_PLAYER_CARD_BUFF: 7214,
    TX_DRAGON_FINISH_HOOK: 7306,
    TX_BUY_GATHER_SPIRIT: 7507,
    TX_GODOTS_MORDOR_RESET: 7510,
    TX_BUY_ZONGZI: 7702,
    TX_ZONGZI_EXCHANGE: 7707,
    ASTERISM_FUBEN_BUY_ATTACK: 7906,
    TX_ASTERISM_REVIVE: 7907,
    TX_TOP_DUEL_RESET: 8004,
    TX_BETA_ACTIVITY_BUY_GIFT: 8202,
    TX_BUY_LEVEL_GIFT_ACTION: 8302,
    TX_WRATH_BUY_ATTACK_TIMES: 8402,
    TX_WRATH_CLEAN_CD: 8403,
    TX_COMMON_EXCHANGE_EXCHANGE: 8602,
    TX_CLEAR_JOIN_COOL: 9109,
    TX_CLEAR_UPDATE_FIGHT_CD: 9119,
    TX_TOP_UP_ACTIVITIES_GIFT: 9302,
    TX_TOP_UP_ACTIVITIES_SEND_GIFT_ACTION: 9305,
    TX_BUY_CHRISTMASGOOD: 11502,
    TX_BUY_SPECIAL_ITEM: 11806,
    TX_CLEAN_CD_TIME: 11807,
    TX_NEWYEAR_BUY_CHRISTMASGOOD: 11902,
    TX_NEWYEAR_BUY_HORSE: 11908,
    TX_ARTIFACT_BUY_GIFT: 12102,
    TX_SECKILL_BUY_GIFT: 12302,
    TX_DRAGON_TREASURE_REVIVE: 12504,
    TX_DRAGON_TREASURE_BUY_DEGREE: 12505,
    TX_BUY_DRAGON_EQUIP_BAD: 12512,
    TX_ABYSS_DREAM_BUY_DEGREE: 12604,
    TX_MAGIC_RING_BUY_BAG: 12706,
    TX_COIN_SHAKE_BUY: 12802,
    TX_BUY_CARD: 13201,
    TX_RENEW_CARD: 13202,
    TX_SEND_CARD: 13205,
    MYSTERIOUS_BUY: 13601,
    TX_MAGIC_GUARD: 13811,
    CLEAR_CD: 14007,
    TX_DAILY_PREFERENTIAL: 14102,
    TX_MOON_CLEAR_CD: 14412,
    TX_DISCOUNT_MALL_BUY_GOODS: 15001,
    TX_BUY_RANDOM_COUNT: 15399,
    TX_SOULPALACE: 15702,
    TX_DEVILABYSS_HAVEN_BUY: 16210,
    TX_DEVILABYSS_ENTER_LAIR: 16250,
    TX_DEVILABYSS_ENTER_PALIN: 16260,
    TX_EXTREME_BUY: 16402,
    ROCKFIGHT_ROCK_OPPOSE: 67101,
    ROCKFIGHT_BUFF: 67104,
    ROCKFIGHT_BUY_ROCK_COUNT: 67106,
    ROCKFIGHT_BUFF_OPPOSE_TEAM: 67107,
    TRAVEL_BUY_TICKET: 70008,
    TRAVEL_BUY_SHOP: 70009,
    TRAVEL_COOL_TIME: 70011,
    TX_WEDDING_TRIP_OPEN: 81105,
    TX_MARRY_RETRIEVE: 81205,
    TX_MARRY_STARTUP_MARRY: 81402,
    TX_MARRY_DATE_MARRY: 81406,
    TX_MARRY_BLESS: 81409,
    TX_MARRY_CANDY: 81413,
    TX_KNOT_RAIN: 81504,
    TX_CHAMPION_PAY: 88304,
    TX_CHAMPION_PAY_REWARD: 88305,
    TX_FLOWER: 88306,
    TX_EGG: 88307,
    TX_FAIRY_LOVE: 110102,
    TX_BUY_FAIRY_TREE_LOVE: 110204,
    TX_STRONGEST_CHAMPION_PAY_REWARD: 117305,
    TX_STRONGEST_FLOWER: 117306,
    TX_STRONGEST_EGG: 117307,
    TX_STRONGEST_CLEAR_UPDATE_FIGHT_CD: 117402,
  },
  BattleDesignCmd: {
    QUERY_TATTO: 1,
    UPGRADE_TATTO: 2,
    TRAIN_TATTOO: 3,
  },
  BetaActivityCmd: {
    CHECK_IS_BUY: 1,
    BUY_GIFT: 2,
  },
  BlueCDKeyGiftCmd: {
    HAD_DRAWED: 1,
    DRAW_GIFT: 2,
    PUSH_CDKey_GIFT: 3,
  },
  BoatFestivalCmd: {
    GET_MY_BOAT_FESTIVAL: 1,
    BUY_ZONG_ZI: 2,
    INVITE: 3,
    REINVITE: 4,
    LEAVE: 5,
    EAT_ZONG_ZI: 6,
    EXCHANGE: 7,
    GET_INVITE_LIST: 8,
    EAT_AGAIN: 9,
    PUSH_INVITE: 1001,
    PUSH_REINVITE: 1002,
    PUSH_LEAVE: 1003,
    PUSH_EAT_ZONG_ZI: 1004,
    PUSH_EAT_AGAIN: 1005,
  },
  BraveBattleCmd: {
    GET_BRAVE_BATTLE_LIST: 1,
    ENTER: 2,
    LEAVE: 3,
    GET_STATUS: 4,
    LINE_UP: 5,
    ENHANCE_FIGHT_ATTR: 6,
    BUY_CARTRIDGE: 7,
    GET_POINTS: 8,
    EXCHANGE: 9,
    WATCH: 10,
    BET: 11,
    PUSH_START: 1001,
    PUSH_END: 1002,
    PUSH_USER_STATUS: 1003,
    PUSH_LINE_UP: 1004,
    PUSH_BUY_CARTRIDGE: 1005,
    PUSH_BATTLE: 1006,
    REVIVEMYSELFT: 10001,
  },
  BraveReturnGiftCmd: {
    CHECK_FIRST_COMEBACK_INFO: 1,
    DRAW_FIRST_COMEBACK_GIFT: 2,
  },
  CatchBeastCmd: {
    OPEN_CATCHBEAST: 1,
    CLOSE_CATCHBEAST: 2,
    BROADCAST_MOVE: 3,
    SWITCH_CATCHBEAST: 4,
    CLICK_MONSTER: 5,
    BUY_SPECIAL_ITEM: 6,
    CLEAN_CD_TIME: 7,
    GET_CD_TIME: 8,
    PUSH_MOVE: 100,
    PUSH_NEW_ROOM_USER: 101,
    PUSH_CATCHBEAST_OPEN: 102,
    PUSH_LEFT_ROOM: 103,
    PUSH_REFRESH_MONSTER: 104,
  },
  CaveCmd: {
    COLSE_CAVE: 2,
    CREATE_TEAM: 3,
    APPLY_JOIN: 4,
    SORT_MEMBER: 5,
    LEFT_TEAM: 6,
    KICK_MEMBER: 7,
    APPLY_LEADER: 8,
    HANDLE_APPLY_LEADER: 9,
    INVITE_MEMBER: 10,
    HANDLE_INVITE_MEMBER: 11,
    GET_TEAM_LIST: 13,
    GET_INVITEVO_LIST: 14,
    QUERY_MY_APPLY: 15,
    CANCEL_APPLY: 16,
    QUERY_TEAM: 17,
    ANSWER_APPLY_JOIN: 18,
    CLAIM_LEADER_WITHOUT_NO_ANSWEER: 19,
    TRANSFER_LEADER: 20,
    MOVE: 101,
    SWITCH_CAVE: 102,
    RECEIVE_TASK: 201,
    REWARD_TASK: 202,
    ATTACK_TASK_MONSTER: 203,
    EXCAVATE: 204,
    BROADCAST_OPERATION: 205,
    GENERATE_EXCAVATE_NO: 206,
    GENERATE_QUESTION: 207,
    ANSWER_QUESTION: 208,
    RECEIVE_TASK_WITH_ITEM: 209,
    QUERY_MY_TEAM: 304,
    QUERY_PROFITS: 305,
    ATTACK_BOSS: 401,
    PUSH_TEAM_CHANGES: 1001,
    PUSH_TEAM_MOVE: 1002,
    PUSH_TEAM_MOVE_VO: 1003,
    PUSH_TEAM_TASK: 1004,
    PUSH_FIGHT: 1005,
    PUSH_LEFT_CAVE: 1007,
    PUSH_LEADER_OPERATION: 1008,
    PUSH_EXCAVATE_NO: 1009,
    PUSH_EXCAVATE_RESULT: 1010,
    PUSH_SCENE_REISZE: 1011,
    PUSH_SWITCH_CAVE: 1012,
    PUSH_APPLY: 1013,
    PUSH_APPLY_ANSWER: 1014,
    PUSH_INVITED: 1015,
    PUSH_TEAM_CHANGES_TO_LIST_VIEWERS: 1016,
    PUSH_REPLACE_LEADER_REQUEST: 1017,
    PUSH_ANSWER_REPLACE_LEADER_REQUEST: 1018,
    PUSH_TEAM_MOVER_STATUS: 1020,
    PUSH_QUESTION_TO_MEMBERS: 1021,
    PUSH_ANSWER_TO_MEMBERS: 1022,
    PUSH_CAVE_OPEN: 1023,
    PUSH_USE_CBT: 1024,
    PUSH_TEAM_ATTACK_BOSS: 1025,
    PUSH_BOSS_OVER: 1026,
    PUSH_BOSS_OPEN: 1027,
    CAVE_ATTACK_FIGHT_OVER_ACTION: 350002,
    CAVE_AUTO_RUN_TARGET_ACTION: 350003,
    CAVE_TEAM_SCENE_MEMBER_MOVE: 350004,
    CAVE_TEAM_SCENE_CHANGE_MEMBER: 350005,
    CAVE_TEAM_SCENE_CHANGE_REISZE: 350006,
    CAVE_TEAM_SCENE_LEAVE_SCENE: 350007,
    CAVE_TEAM_SCENE_MOVER_STATUS: 350008,
    CAVE_LEFT_TEAM_QUIT_SCENE: 350100,
  },
  ChatCmd: {
    SEND_CHAT_MESSAGE: 1,
    CHAT_PUSH: 2,
    CHAT_SHOW_USEREQUIP: 3,
    CHAT_NOTICE: 4,
    DA_LA_BA: 5,
  },
  ChristmasCmd: {
    ENTER_CHRISTMAS: 1,
    BUY_CHRISTMASGOOD: 2,
    ENTER_LOTTERY: 5,
    DECORATION_LOTTERY: 6,
    REWARD_LOTTERY: 7,
  },
  ChristmasFestivalCmd: {
    CHRISTMASFESTIVAL_ENTER: 1,
    CHRISTMASFESTIVAL_DISMANTLE_GIFT: 2,
    CHRISTMASFESTIVAL_TURNTABLE: 3,
  },
  ClothesCmd: {
    MY_CLOTHES: 1,
    UNLOCK_CLOTHES: 2,
    USE_CLOTHES_CARD: 3,
    DRESS: 4,
    UNDRESS: 5,
    HIDDEN: 6,
    RENEWAL: 7,
    PROMPT: 8,
    IS_EXPIRE: 9,
    GET_CLOTHES_ABILITY: 10,
    QUERY_CLOTHES_BOX_RANK: 11,
    USE_ITEM_ADDITION: 12,
    USE_ITEM: 13,
    SELECT_ITEM: 50,
    CHANGE_SELECT_WAY: 51,
    SET_RENEW_DATA: 52,
    SET_BUY_CLOTHES_DATA: 53,
  },
  CoinShakeCmd: {
    GET_MY_INFO: 1,
    BUY: 2,
  },
  CommonScoreExchangeCmd: {
    GET_MY_INFO: 1,
    EXCHANGE: 2,
    MAGIC_EXCHANGE: 3,
    GET_MAGIC_EXCHANGE_INFO: 4,
  },
  CommonsysCmd: {
    QUEUE_UP: 1,
  },
  ConstellationCmd: {
    ENTER_CONSTELL: 1,
    LEVELUP_CONSTELL: 2,
  },
  ContinuedLoginCmd: {
    GET_USERS_ERIESLOGIN: 1,
    TAKE_REWARD: 2,
  },
  CrossBattleTeamCmd: {
    QUERY_MY_TEAM: 1,
    VIEW_TEAM: 2,
    CREATE_TEAM: 3,
    JOIN_TEAM: 4,
    INVITE_JOIN: 5,
    MODIFY_PASSWORD: 6,
    QUIT_TEAM: 7,
    KICK_MEMBER: 8,
    CLEAR_JOIN_COOL: 9,
    QUERY_FIGHT_LAYOUT: 10,
    SET_FIGHT_LAYOUT: 11,
    APPLY: 12,
    UPDATE_FIGHT: 13,
    PREPARE_APPLY: 15,
    LIST_JOINABLE_TEAM: 16,
    VIEW_PLAYER_DETAIL: 18,
    CLEAR_UPDATE_FIGHT_CD: 19,
    GET_INVITEVO_LIST: 20,
    PUSH_INVITE_JOIN: 1001,
    PUSH_TEAM_EVENT: 1002,
    PUSH_KICKED: 1003,
  },
  CrossBraveBattleCmd: {
    GET_BRAVE_BATTLE_LIST: 1,
    ENTER: 2,
    LEAVE: 3,
    GET_STATUS: 4,
    LINE_UP: 5,
    ATTEND_REWARD: 6,
    RANK_REWARD: 7,
    PUSH_BATTLE_AREAID: 101,
    PUSH_START: 1001,
    PUSH_END: 1002,
    PUSH_USER_STATUS: 1003,
    PUSH_LINE_UP: 1004,
    PUSH_BATTLE: 1005,
    REVIVEMYSELFT: 10001,
  },
  CrossWarCmd: {
    GET_ACROSS_BATTLE: 101,
    GET_MINI_GROUP_LIST: 102,
    GET_ACROSS_BATTLE_DEAIL: 103,
    GET_CHAMPION_LIST: 104,
    GET_BATTLE_REPORT: 105,
    PREVIOUS_KINGS_LIST: 207,
    MY_MOUNT: 208,
    USE_MOUNT: 209,
    UNUSE_MOUNT: 210,
    PUSH_MOUNT_TIMEOUT: 211,
    PUSH_BATTLE_AREAID: 212,
    HAVE_REWARD: 301,
    GET_CROSS_CHAMPION_DATA: 302,
    EDIT_MESSAGE: 303,
    CHAMPION_PAY: 304,
    CHAMPION_PAY_REWARD: 305,
    FLOWER: 306,
    EGG: 307,
    SUPPORT: 308,
    TEAM_BATTLE_INFO: 309,
    GET_MY_INFO: 312,
    CrossWar_SCHEDULE: 313,
  },
  DailyActiveTaskCmd: {
    QUERY_DAILY_INFO: 1,
    SIGN_IN: 2,
    REWARD_GUIDE: 3,
    REWARD_SIGN: 4,
    RE_SIGN_IN: 5,
    PUSH_NEW_GUIDE_GIFT: 1001,
    PUSH_AUTO_SIGN_IN: 1002,
  },
  DailyPreferentialCmd: {
    ENTER: 1,
    BUY_PREFERENTIAL_GOODS: 2,
  },
  DailyResistBugCmd: {
    ENTER_SCENE: 1,
    LEFT_SCENE: 2,
    CREATE_TEAM: 3,
    LEFT_TEAM: 4,
    JOIN_TEAM: 5,
    INVITE_MEMBER: 6,
    HANDLE_INVITE_MEMBER: 7,
    KICK_MEMBER: 8,
    APPLY_LEADER: 9,
    HANDLE_APPLY_LEADER: 10,
    QUICK_JOIN_TEAM: 11,
    MEMBER_PREPARED: 12,
    SET_AUTO_PREPARED: 13,
    START_RESIST: 14,
    RESIST_BUG: 15,
    GET_MY_TEAM_INFO: 16,
    GET_TEAM_LIST: 17,
    CHANGE_TEAM_PASSWD: 18,
    END_AT_ONCE: 19,
    GET_INVITEVO_LIST: 20,
    APPOINT_LEADER: 21,
    RESIST_STATUS: 22,
    PUSH_RESISTBUG_INFO: 1001,
    PUSH_TEAM_CHANGES: 1002,
    PUSH_INVITE_INFO: 1003,
    PUSH_MEMBER_PREPARED: 1004,
    PUSH_RESIST_INFO: 1005,
    PUSH_RESIST_RESULT: 1006,
    PUSH_RESIST_TURN_ROUND_INFO: 1007,
    PUSH_RESIST_END: 1008,
  },
  DevildomCmd: {
    PUSH_DEVILDOM_STATE_INFO: 1,
    ENTER_DEVILDOM: 2,
    LEFT_DEVILDOM: 3,
    PUSH_USER_CHANGES: 4,
    ATTACK_NPC: 5,
    GET_RANKING_LIST: 6,
    REVIVE_RIGHT_NOW: 7,
    PUSH_DEVILDOM_ARMY_HP_CHANGES: 8,
    ATTACK_RIGHT_NOW: 9,
    GET_REWARD_GIFT: 10,
    FETCH_REWARD_GIFT: 11,
    PUSH_DEVILDOM_FINISHED: 12,
    GET_DEVILDOM_STATUS: 13,
    ENHANCE_FIGHT_ATTR: 14,
    CREATE_ALL_OTHER_PLAYER: 2101,
    ADD_OTHER_PLAYER: 2102,
    REMOVE_OTHER_PLAYER: 2103,
    UPDATE_OTHER_PLAYER_POS: 2104,
    ADD_MONSTER: 2105,
    REMOVE_MONSTER: 2106,
    PLAYER_ATTACK_MONSTER: 2107,
    PLAYER_RELIVE_ATTACK_MONSTER: 2108,
    PLAYER_RELIVE_IMMEDIATE: 2109,
    DEVILDOM_PLAYER_BATTLE_OVER: 2110,
    DEVILDOM_MONSTER_HP_CHANGE: 2111,
    DEVILDOM_IS_SHOW_OTHER_PLAYER: 2112,
  },
  DiscountMallCmd: {
    DISCOUNT_MALL_BUY_GOODS: 1,
  },
  DivineCmd: {
    QUERY_USER_DIVINE: 1,
    DIVINE: 2,
    FINISH: 4,
    DROP: 5,
    REWARD: 6,
    REFRESH: 7,
    RECEIVE: 8,
    DIVINE_WITH_ITEM: 9,
    BUY_DIVINE_TIME: 10,
    PUSH_TASK_CHANGED: 1001,
  },
  DragonBoatCmd: {
    DRAGON_BOAT_VIEW: 1,
    DRAGON_BOAT_ENCOURAGE: 2,
    SET_DRAGON_BOAT_AUTO: 3,
    RAWARD_SCHEDULE: 4,
  },
  DragonFubenCmd: {
    ENTER_AREA: 1,
    ATTACK_MONSTER: 2,
    REWARD_AREA: 3,
    BACK_HOME: 4,
    SORT_FIGHT_POS: 5,
    QUERY_DRAGON_FUBEN: 6,
    QUERY_FIGHT_POS: 7,
    HOOK_AREA: 8,
    FINISH_HOOK: 9,
    CALC_HOOK: 10,
    BATTLE_OVER: 73001,
  },
  DragonTreasureCmd: {
    DRAGON_TREASURE_VIEW: 1,
    DRAGON_TREASURE_DEKARON: 2,
    DRAGON_TREASURE_JUMP_PROCESS: 3,
    DRAGON_TREASURE_REVIVE: 4,
    DRAGON_TREASURE_BUY_DEGREE: 5,
    DRAGON_TREASURE_RESET_SCHEDULE: 6,
    COMBINE_DRAGON_EQUIP: 10,
    COMBINE_ALL_DRAGON_EQUIP: 11,
    BUY_DRAGON_EQUIP_BAD: 12,
    GET_ALL_DRAGON_EQUIP: 13,
    LOCK_DRAGON_EQUIP: 14,
    UNLOCK_DRAGON_EQUIP: 15,
    CHANGE_DRAGON_EQUIP_POS: 16,
    TAKE_EQUIP_IN_BAD: 17,
    TAKE_ALL_EQUIP_IN_BAD: 18,
    BATTLE_OVER: 125003,
    ALL_REWARD: 125004,
  },
  EmailCmd: {
    NEW_EMAIL_ADVICE: 1,
    LIST_ALL_EMAILS: 2,
    SET_BOOKMARK: 3,
    SET_PERSONAL_EMAIL_READED: 4,
    DELETE_EMAILS: 5,
    SEND_PERSONAL_EMAIL: 6,
    SAVE_EMAIL: 7,
    TAKE_EMAIL_ADDITION: 8,
    SEND_ALLIANCE_EMAIL: 9,
    GET_ALL_NEW_EMAIL: 10,
  },
  EmengCmd: {
    ABYSS_DREAM_VIEW: 1,
    ABYSS_DREAM_DEKARON: 2,
    ABYSS_DREAM_SERIES_DEKARON: 3,
    ABYSS_DREAM_BUY_DEGREE: 4,
    USE_POMENG_CARD: 5,
    BATTLE_OVER: 12601,
    UPDATE_SCENE_TIMES: 12602,
  },
  EquipCmd: {
    WEAR: 1,
    UPSTAR: 2,
    FORGE: 3,
    SELECTNEWATT: 4,
    EVOLVEEQUIP: 5,
    UPGRADEEQUIP: 6,
    DIVEQUIP: 7,
    SETJEWEL: 8,
    SHOW_USEREQUIP: 9,
    GETEVOLVEEQUIP: 10,
    SHENZHU_EQUIP: 11,
    JEWEL_CHANGE: 12,
    JEWEL_BUFF_UPGRADE: 13,
    JEWEL_BUFF_AUTO_UPGRADE: 14,
    MY_JEWEL_BUFF_INFO: 15,
    INLAY: 16,
    NUDE: 26,
  },
  ExtremeGiftCmd: {
    EXTREME_VIEW: 1,
    EXTREME_BUY: 2,
  },
  FairyCmd: {
    FAIRY_VIEW: 101,
    FAIRY_EXPRESS_LOVE: 102,
    FAIRY_UNLOCK: 103,
    FAIRY_CARESS: 104,
    FAIRY_UP_STAR: 105,
    FAIRY_EVOLUTION: 106,
    FAIRY_SET_FIGHT: 107,
    FOLLOW: 108,
    GET_FAIRY_TREE_BUFF: 201,
    ENTER_FAIRY_TREE: 202,
    FAIRY_TREE_LOVE: 203,
    BUY_FAIRY_TREE_LOVE: 204,
    ACTIVATE_FAIRY_TREE_BUFF: 205,
    GET_USER_FAIRY: 301,
    INHERITANCE: 302,
    SOUL_UNLOCK: 401,
    SOUL_UPLEVEL: 402,
    PUSH_FAIRY_TREE_BUFF_EXPIRE: 2001,
  },
  FarmCmd: {
    ENTER: 1,
    EXIT: 2,
    GET_STATUS: 3,
    SOW: 4,
    REMOVE: 5,
    GAIN: 6,
    STEAL: 7,
    FRIEND_LIST: 8,
    QUICK: 9,
    OPERATION: 10,
    PRAY: 11,
    ADD_SPIRIT: 12,
    LOGS: 13,
    STORE: 14,
    GET_LOGIN_STATUS: 15,
    HELP_FRIEND_SPEED_UP: 16,
    LAND_UPGRADE: 17,
    ADD_LAND_EXP: 18,
    PUSH_LAND_STATUS: 100,
    PUSH_FARM_STATUS: 101,
    PUSH_FARM_UPGRADE: 102,
    PUSH_MASTER_INCOME: 103,
  },
  FarmSlaveCmd: {
    GET_THIEFS: 1,
    GET_ROBBERS: 2,
    GET_OLD_MASTERS: 3,
    REVOLT_MASTER: 4,
    RANSOM: 5,
    RELEASE_SLAVE: 6,
    GET_SLAVES: 7,
    BUY_SAVE_TIMES: 8,
    GET_SLAVE_LOGS: 9,
    CAPTURE_SLAVE: 10,
    BUY_CAPTURE_TIMES: 11,
    SAVE_SLAVE: 12,
    GET_EXPIRE: 13,
    GET_FRIENDS: 14,
    GET_ALLIANCE_FRIENDS: 15,
    SAVE_SLAVE_BATTLE_WITH_MASTER: 16,
    GET_CAPICITY: 17,
    GET_CAPTURE_CD_TIME: 18,
    CLEAR_CAPTURE_CD_TIME: 19,
    SAVE_SLAVE_GET_MASTERNAME: 20,
  },
  FeastCmd: {
    ENTER_FEAST: 1,
    PVP: 2,
    GET_RANKING_LIST: 3,
    REVIVE_RIGHT_NOW: 4,
    LEAVE_FEAST: 5,
    TIME_REWARD: 6,
    STATE_BROADCAST: 7,
    GET_FEAST_STATUS: 8,
    GET_USER_STATUS: 9,
    GET_USER_COUNT: 10,
    BUY_CD: 12,
    BATTLE_FEAST_STATE: 1001,
    PUSH_USER_CHANGES: 1002,
    PUSH_FEAST_FINISHED: 1003,
    PUSH_AI_MANGER: 1004,
    PUSH_AI_JOIN: 1005,
    WIN_DEAD: 2001,
    WIN_LIVE: 2002,
    WIN_UPDATE_LIST: 2003,
    WIN_UPDATE_PLAYERS: 2004,
    WIN_IN_BATTLE: 2005,
    WIN_OUT_BATTLE: 2006,
    WIN_TEST_DEAD: 2007,
    WIN_ONE_LIVE: 2008,
    WIN_FLUSH_HP: 2009,
    SCENE_MOVE: 2010,
    AUTO_MOVE: 2011,
    WIN_ENTER_MAP: 2012,
    UPDATE_POSITION: 2013,
    UPDATE_STATUS: 2014,
    UDPATE_RANK_ICON: 2015,
    JUDEGE_REWARD_LIMIT: 2016,
    OPEN_FIGHTCD_TIME: 2017,
    FLUSH_SELF_STATE: 2018,
    FEAST_HARD_CLOSE: 2019,
    FEAST_AI_UPDATE: 2020,
    AI_ATTACK: 2021,
    AI_ADD: 2022,
    AI_MOVE: 2023,
    AI_ATTACK_F: 2024,
  },
  FightCmd: {
    GET_MY_FIGHT_INFO: 1,
    REQUEST_FIGHT: 2,
    HANDLE_FIGHT_REQUEST: 3,
    PUSH_REQUEST_FIGHT: 1001,
    PUSH_HANDLE_FIGHT_REQUEST: 1002,
  },
  FinancialPlanCmd: {
    BUY_PLAN: 1,
    REWARD_PLAN: 2,
    QUERY_MONEY_PLAN: 3,
  },
  FiveFiveDayCmd: {
    FIVEFIVEDAY_VIEW: 1,
    FIVEFIVEDAY_MAKE: 2,
    FIVEFIVEDAY_EAT: 3,
    FIVEFIVEDAY_OPEN_GIFT: 4,
    FIVEFIVEDAY_RANK_LIST: 5,
    FIVEFIVEDAY_SRVREWARD: 6,
    FIVEFIVEDAY_PUSH_DYNAMIC: 1000,
    FIVEFIVEDAY_PUSH_REFRESH: 1001,
  },
  FlyingCmd: {
    PICK_ITEM: 1,
    QUERY_FLYING: 2,
    TAKE_PART: 3,
    SET_FLYING_FLAG: 4,
    PUSH_FLYING_STATUS: 1001,
    PUSH_FLYING_DROP: 1002,
    PUSH_FLYING_BEGIN: 1003,
    PUSH_FLYING_FINISH: 1004,
    PUSH_FLYING_MOVING: 1005,
    PUSH_FLYING_TIME_OUT: 1006,
    PUSH_EXIT_FLYING: 1007,
    PUSH_FLYING_RANK: 1008,
  },
  FoolDayCmd: {
    FOOL_DAY_VIEW: 1,
    FOOL_DAY_FIRST_RANDOM: 2,
    FOOL_DAY_SECOND_RANDOM: 3,
    FOOL_DAY_SRVREWARD: 4,
    FOOL_DAY_GET_SENDER_LIST: 5,
    FOOL_DAY_SEND_BOX: 6,
    FOOL_DAY_REWARD_BOX: 7,
    FOOL_DAY_VIEW_BOX: 8,
  },
  FriendCmd: {
    FRIEND_ADDFRIEND: 1,
    FRIEND_ADDBLACK: 2,
    FRIEND_GETFRIEND: 3,
    FRIEND_DELETEFRIEND: 4,
    CAN_BE_FRIEND: 6,
    BATCH_ADDFRIEND: 7,
    GETFRIENDLV: 8,
    USE_FLOWER: 9,
    ISONLINE: 10,
    BLESS: 11,
    GET_RELATIONBLESS: 12,
    GET_RELATIONWHERE: 13,
    SET_WHERE: 14,
    BLESS_ABILITY: 15,
    GET_INVITEVO_LIST: 16,
    PUSH_OPEN_PARTY: 462,
    PUSH_ADDFRIEND: 1001,
    PUSH_DELRELATION: 1002,
    PUSH_FRIEND_LV_UP: 1003,
    PUSH_FRIEND_ABILITY_LV_UP: 1004,
  },
  FriendShipCmd: {
    BUY_FRIEND_SHIP_ITEM: 1,
    GET_FRIEND_SHIP_VALUE: 2,
    PUSH_FRIEND_SHIP: 100,
  },
  FubenCmd: {
    QEURY_FIRST_BREAK: 1,
    ENTER_SINGLE_AREA: 2,
    ATTACK_MONSTER: 3,
    REWARD_AREA: 4,
    HOOK_AREA: 5,
    FINISH_HOOK: 6,
    CALC_HOOK: 7,
    BACK_HOME: 8,
    DRAW_EXTRA_ENERGY: 9,
    PUSH_TIME_POINT: 1001,
    PUSH_FIRST_BREAK: 1002,
    FUBEN_GO_TO_MAP: 100001,
    FUBEN_ROLE_WALK_POINT: 100002,
    FUBEN_UPDATE_TASK_STATE: 100003,
    FUBEN_ROLE_UPDATE_LEVEL_EFF: 100004,
    FUBEN_ROLE_WING_GRADE_UPDATE: 100005,
    FUBEN_FIGHT_STATE: 100006,
    FUBEN_BG_BLUR: 100007,
    PLAY_FUBEN_END_ANIMATION: 100008,
    FUBEN_CREATE_MONSTER: 100009,
    FUBEN_WALK_TO_TARGET: 100010,
  },
  FundCmd: {
    BUY_FUND: 1,
    GET_AWARD_LIST: 2,
    GET_SEND_LIST: 3,
    SEND_FUND: 4,
    RECEIVE_FUND: 5,
    REWARD_SEND_FUND_GIFT: 6,
  },
  GMCmd: {
    SET_MONEY: 1,
  },
  GameActCmd: {
    QUERY_ACTIVITY: 1,
    REWARD_ACTIVITY: 2,
    REWARD_FIRST_CHARGE: 3,
    QUERY_SUGGEST_ACTIVITY: 4,
    EXCHANGE_ITEM: 5,
    REWARD_TUAN_ACTIVITY: 6,
    PUSH_NEW_ACTIVITY_COMING_REWARD: 1001,
    PUSH_TUAN_GIFT: 1002,
  },
  GiftCmd: {
    LIST_BASE_GFIT: 1,
    LIST_USER_GFIT: 2,
    RECEIVE_GFIT: 3,
    RECEIVE_SEQUENCE_GIFT: 4,
    RECEIVE_ONLINE_TIME_GIFT: 5,
    QUERY_ONLINE_TIME_GIFT: 6,
    RECEIVE_LOGIN_GIFT: 7,
    RECEIVE_COST_GIFT: 8,
    BUY_COST_GIFT: 9,
    REWARD_ENTRANCE_GIFT: 10,
    REWARD_TASK_MARKET: 11,
    REWARD_SMALL_CONSUME_GIFT: 12,
    REWARD_PF_ONLINE_GIFT: 13,
    QUERY_SIGN_IN_INFO: 14,
    SIGN_IN: 15,
    REWARD_SIGN_SINGLE: 16,
    REWRD_SIGN_LX: 17,
    GET_TOTAL_CONSUME_GOLD: 18,
    PUSH_NEW_BASE_GIFT: 1001,
    PUSH_NEW_USER_GIFT: 1002,
    PUSH_DELETE_BASE_GIFT: 1003,
    PUSH_USER_TIMED_MONEY: 1004,
    PUSH_GIFT_REFRESHED: 1005,
    PUSH_SEQUENCE_GIFT: 1006,
    PUSH_TASK_MARKET_GIFT: 1007,
  },
  GillyCmd: {
    GETSLAVESYSDETAIL: 2,
    CAPTURESLAVE: 3,
    SAVESLAVE: 4,
    MASTER_OR_SLAVES: 5,
    GET_TARGET_SLAVEVO: 6,
    GET_HISTORYEVENT: 7,
    PUSH_HISTORY: 9,
    REVOLT_MASTER: 10,
    RANSOM: 11,
    RELEASE_SLAVE: 12,
    RECIPROCAL: 13,
    CAPTURECOOLING: 14,
    GET_SLAVEBATTLEVO: 15,
  },
  GodOtsCmd: {
    GET_ALL_CARD_VO: 1,
    COMBIN_HERO_CARD: 2,
    COMBIN_DRAGON_CARD: 3,
    JINHUA_CARD: 4,
    USE_RUNE_CARD: 5,
    DRAW_HERO_CARD: 6,
    EXCHANGE_GOODS: 7,
    GET_MY_CARD_COLLECTIONS: 8,
    BUY_PACK_SIZE: 9,
    GET_DRAGON_PRAY: 10,
    PRAY: 11,
    CLEAR_PRAY_CD_TIME: 12,
    EXCHANGE_PLAYER_CARD_BUFF: 14,
    GET_PLAYER_CARD: 15,
  },
  GodWeaponCmd: {
    UNLOCK: 1,
    UPSTAR: 2,
    UPGRADE: 3,
    GET_ARTIFACT: 4,
    SUBLIMATION: 5,
  },
  GodWingCmd: {
    ACTIVE_GODWING: 1,
    WING_UPSTAR: 2,
    TOTAL_WING_ABILITY: 3,
    MY_MAGIC_WING: 4,
    UNLOCK_MAGIC_WING: 5,
    DISPLAY: 6,
    TRAIN_MAGIC_WING: 7,
    SAVE_TRAIN_MAGIC_WING: 8,
    RESET_MAGIC_WING_ATTR: 9,
    MAGIC_WING_BREAK: 10,
    PUSH_GODWINGVO: 1001,
  },
  GoddessCmd: {
    GODDESS_RESET: -1,
    GODDESS_ENTER: 1,
    GODDESS_PRAY: 2,
    GODDESS_SYNC: 3,
  },
  GodotsMordorCmd: {
    MY_DRAGONS: 1,
    WAKE_UP: 2,
    ON_BATTLE: 3,
    GRAIN_UPGRADE: 4,
    GET_TEAM_FORMATION: 5,
    SET_TEAM_FORMATION: 6,
    GET_GATHER_SPIRIT: 7,
    UPGRADE: 8,
    LEARN_SKILL: 9,
    RESET: 10,
    FOLLOW: 11,
    AWAKEN_UP_LEVEL: 12,
    PUSH_DRAGON_ATTR: 1001,
  },
  GroupBuyCmd: {
    ENTER_GROUPBUY: 1,
    ORDER: 2,
    PAY: 3,
    GIVEUP: 4,
    EXCHANGE: 5,
    EXCHANGE_SHOP: 6,
  },
  GuardCmd: {
    VIEW: 1,
    UPLEVEL: 2,
    SET_FOLLOW: 3,
    MAGIC_TRAIN: 11,
    MAGIC_SET_DEFAULT: 12,
    MAGIC_UNLOCK: 13,
  },
  GymCmd: {
    DO_GYM: 1,
    CAL_GYM: 2,
    TAKE_BLESS: 3,
    FINISH_GYM: 4,
    GET_USERGYMVO: 5,
    ROB_TOOL: 6,
    GET_TOOLLIST: 7,
    GET_GYM_OPEN: 8,
    GET_OUT_LINE_EXP: 9,
    USE_GYM_CARD: 10,
    PUSH_ROB_TOOL: 1001,
    PUSH_GYM_OPEN: 1002,
  },
  HitEggsCmd: {
    QUERY_INVITE: 1,
    QUERY_RECALL: 2,
    QUERY_SHARE: 3,
    HIT_EGG: 4,
    REWARD_TASK: 5,
  },
  HonorCmd: {
    PUSH_HONOR_TIME_OUT: 11,
  },
  LevelUpGiftCmd: {
    CHECK_GIFT: 1,
    BUY_GIFT: 2,
    PUSH_GIFT: 10001,
  },
  LoginLotteryCmd: {
    LOGIN_LOTTERY_GET_USERCONTINLOGIN: 1,
    LOGIN_LOTTERY_DRAW_CARD: 2,
    LOGIN_LOTTERY_TAKE_REWARD: 3,
    LOGIN_LOTTERY_DRAW_ALL_CARD: 4,
  },
  LongyuanCmd: {
    QUERY_DRAGONYUAN: 1,
    ACTIVITY_DRAGONYUAN: 2,
    UPLEVEL_DRAGONYUAN: 3,
    UPGRADE_DRAGONYUAN: 4,
    USEITEM_DRAGONYUAN: 5,
    GET_SKILLS: 10,
    SET_SKILL: 11,
    AUTO_UPLEVEL_DRAGONYUAN: 12,
    AUTO_UPGRADE_DRAGONYUAN: 13,
  },
  LuckyBagCmd: {
    LUCKY_BAG_ENTER: 1,
    LUCKY_BAG_OPEN_BAG: 2,
    LUCKY_BAG_DRAW_BAG_BOX: 3,
    LUCKY_BAG_DRAW_SERVER_REWARD: 4,
  },
  LuckyTurntableCmd: {
    GET_FORTUNEWHEEL_INFO: 1,
    PLAY_FORTUNEWHEEL: 2,
    RESET_FORTUNEWHEEL: 3,
  },
  MagicRingCmd: {
    LIST_RING: 1,
    COMBINE_RING: 2,
    COMBINE_ALL_RING: 3,
    LOCK_RING: 4,
    UNLOCK_RING: 5,
    BUY_BAG: 6,
    TAKE_RING_TO_BAG: 7,
    CHANGE_RING_POS: 8,
    LIST_RING_INFO: 9,
    ABYSS_UPGADE_RING_QUALITY: 21,
    ABYSS_INLAY_RING: 22,
    ABYSS_TEAR_DOWN_RING: 23,
    DEMONS_SUPPRESS: 30,
    DEMONS_SEAL: 31,
    PRINT_SEAL: 36,
    SHORTCUT_SEAL: 37,
  },
  MallCmd: {
    BUY_ITEM: 1,
    LIST_SHOPGOOD_ACTIVITY: 2,
    LIST_ACTIVITYGOOD: 3,
    GET_SEND_LIST: 4,
    SEND_ITEM: 5,
    PUSH_SHOP_REFRESH: 1001,
  },
  MarketCmd: {
    PAGE_MARKET_SELL: 1,
    LIST_MY_SELL: 2,
    QUERY_MY_SELL_COUNT: 3,
    LIST_BAG: 4,
    BUY: 5,
    CANCEL_SELL: 6,
    FETCH_TO_PACK: 7,
    SELL_ITEM: 8,
    SELL_EQUIP: 9,
    OPEN_MARKET_CERTIFY: 10,
    MARKET_STORE_DIV: 11,
  },
  MarryCmd: {
    REQUEST_MARRY: 101,
    HANDLE_MARRY_REQUEST: 102,
    RECORD_MARRY: 103,
    WEDDING_TRIP_LIST: 104,
    WEDDING_TRIP_OPEN: 105,
    WEDDING_TRIP_INVATE: 106,
    HANDLE_WEDDING_TRIP_INVATE: 107,
    WEDDING_TRIP_STOP: 108,
    REQUEST_DIVORCE: 109,
    FIND_DIVORCE_REQUEST: 110,
    CANCEL_DIVORCE: 111,
    PUSH_REQUEST_MARRY: 112,
    PUSH_HANDLE_MARRY_REQUEST: 113,
    PUSH_REQUEST_WEDDING_TRIP: 114,
    PUSH_HANDLE_WEDDING_TRIP: 115,
    PUSH_DIVORCE: 116,
    PUSH_OPEN_WEDDING_TRIP: 117,
    PUSH_SCENSE_WEDDING_TRIP: 118,
    PUSH_STOP_WEDDING_TRIP: 119,
    MARRY_ENTER_GIFT_TO_PARTNER: 120,
    MARRY_GIVE_GIFT_TO_PARTNER: 121,
    MARRY_PUSH_DIVORCE: 122,
    MY_RING: 201,
    UPGRADE: 202,
    UNLOCK: 203,
    MARRY_RETRIEVE_VIEW: 204,
    MARRY_RETRIEVE: 205,
    MARRY_CULTIVATE: 206,
    PARTNERCHOTHESDATA: 207,
    PARTNERFAIRYDATA: 208,
    RECEIVECHOTHESTEMPEXP: 209,
    RECEIVEFAIRYTEMPEXP: 210,
    AUTORECEIVECHOTHESTEMPEXP: 211,
    AUTORECEIVEFAIRYTEMPEXP: 212,
    TEMPEXPLIST: 213,
    REC_GUARD_EXP: 214,
    REC_ALL_GUARD_EXP: 215,
    GUARD_TEMP_EXP_VIEW: 216,
    QUERY_TCLY: 301,
    UPGRADE_HEART: 302,
    ENTER_MARRY: 401,
    STARTUP_MARRY: 402,
    INTO_MARRYROOM: 403,
    USER_MOVE: 404,
    LEAVE_MARRYROOM: 405,
    DATE_MARRY: 406,
    SEND_MARRY_LETTER: 407,
    REQUST_MARRY_BLESS: 408,
    BLESS_MARRY: 409,
    INVITE_MARRY: 410,
    START_MARRY: 411,
    REQUST_MARRY_CANDY: 412,
    SEND_MARRY_CANDY: 413,
    PUSH_MARRY_START: 450,
    PUSH_USERENTERSECNE: 451,
    PUSH_USERMOVE: 452,
    PUSH_USERLEAVESECNE: 453,
    PUSH_USERSTART: 454,
    PUSH_USERDATE: 455,
    PUSH_INVITE: 456,
    PUSH_BLESS: 457,
    PUSH_CANDY: 458,
    PUSH_ROOM_END: 459,
    PUSH_WEDDINGRESOUCE: 460,
    PUSH_EXPR_PROFIT: 461,
    KNOT_QUERY_MARRIAGE_TREE: 501,
    KNOT_IRRIGATE_MARRIAGE_TREE: 502,
    KNOT_SEND_PROP: 503,
    KNOT_RAIN: 504,
    KNOT_BLESSING: 505,
    KNOT_CONVERT: 506,
    KNOT_PUSH_ENTERSECNE: 507,
    KNOT_PUSH_MOVE: 508,
    KNOT_PUSH_LEAVESECNE: 509,
    KNOT_INTO_RAIN_ROOM: 510,
    KNOT_USER_MOVE_RAIN: 511,
    KNOT_LEAVE_RAIN_ROOM: 512,
    KNOT_QUERY_RAIN_LIST: 513,
    KNOT_PUSH_MARRIAGETREEVO: 514,
  },
  MedalCmd: {
    GET_USER_MEDAL: 1,
    UP_GRADE_MEDAL: 2,
    CAL_UP_GRADE: 3,
    SKILL_UPGRADE: 4,
    AUTO_SKILL_UPGRADE: 5,
  },
  MonthCardCmd: {
    BUY_CARD: 1,
    RENEW_CARD: 2,
    REWARD_DAYGIFTS: 3,
    GET_SEND_LIST: 4,
    SEND_CARD: 5,
    REWARD_FIFST_GIFTS: 6,
    GET_CARD_LIST: 7,
    PUSH_CARD_LIST: 101,
  },
  MoonFestivalCmd: {
    MOONFESTIVAL_ENTER: 1,
    MOONFESTIVAL_EAT_MOON_CAKES: 2,
    MOONFESTIVAL_DRAW_SERVER_REWARD: 3,
    MOONFESTIVAL_DRAW_NODE_REWARD: 4,
    MOON_ATTACK: 11,
    MOON_CLEAR_CD: 12,
    MOON_SAVE_REWARD: 13,
    PUSH_MOON_SAVE_DYNAMIC: 1000,
  },
  MultiArenaCmd: {
    ENTER_SCENE: 1,
    LEFT_SCENE: 2,
    CREATE_TEAM: 3,
    JOIN_TEAM: 4,
    SORT_MEMBER: 5,
    LEFT_TEAM: 6,
    KICK_MEMBER: 7,
    APPLY_LEADER: 8,
    HANDLE_APPLY_LEADER: 9,
    INVITE_MEMBER: 10,
    HANDLE_INVITE_MEMBER: 11,
    GET_MY_TEAM_INFO: 12,
    GET_MULTIFUBEN_TEAM_LIST: 13,
    GET_MULTIFUBEN_INVITEVO_LIST: 14,
    MEMBER_PREPARED: 15,
    START_HUNT: 16,
    OPEN_BOX: 17,
    BUY_GOODS: 18,
    SET_AUTO_PREPARED: 19,
    TRANSFER_LEADER: 20,
    MEMBER_MOVE: 21,
    CHANGE_TEAM_PASSWD: 22,
    QUICK_JOIN_TEAM: 23,
    START_HUNT_WITH_DRAGON: 24,
    RECEIVE_REWARD: 25,
    PUSH_MULTIARENA_INFO: 1001,
    PUSH_TEAM_CHANGES: 1002,
    PUSH_INVITE_INFO: 1003,
    PUSH_HUNT_INFO: 1004,
    PUSH_BOX_RESULT: 1005,
    PUSH_MEMBER_PREPARED: 1006,
    PUSH_MEMBER_MOVE: 1007,
  },
  MultifubenCmd: {
    ENTER_SCENE: 1,
    LEFT_SCENE: 2,
    CREATE_TEAM: 3,
    JOIN_TEAM: 4,
    SORT_MEMBER: 5,
    LEFT_TEAM: 6,
    KICK_MEMBER: 7,
    APPLY_LEADER: 8,
    HANDLE_APPLY_LEADER: 9,
    INVITE_MEMBER: 10,
    HANDLE_INVITE_MEMBER: 11,
    GET_MY_TEAM_INFO: 12,
    GET_MULTIFUBEN_TEAM_LIST: 13,
    GET_MULTIFUBEN_INVITEVO_LIST: 14,
    START_FUBEN: 15,
    ATTACK_NPC: 16,
    MEMBER_PREPARED: 17,
    GET_FUBEN_HIS: 18,
    SET_AUTO_PREPARED: 19,
    MEMBER_MOVE: 20,
    MOVE_TO_TELEPORT: 21,
    SEND_INVITATION: 22,
    JOIN_TEAM_BY_INVITATION: 23,
    TRANSFER_LEADER: 24,
    CHANGE_FUBEN: 25,
    CHANGE_USE_COUNT: 26,
    GET_REWARDS: 27,
    FIGHT_REPORT_PLAY_END: 28,
    CHANGE_TEAM_PASSWD: 29,
    PUSH_START_FUBEN: 1001,
    PUSH_ATTACK_NPC: 1002,
    PUSH_TEAM_CHANGES: 1003,
    PUSH_INVITE_INFO: 1004,
    PUSH_MEMBER_PREPARED: 1005,
    PUSH_MEMBER_MOVE: 1006,
    PUSH_ENTER_NEXT_AREA: 1007,
    PUSH_SEND_INVITATION: 1008,
    PUSH_FIGHT_REPORT_PLAY_END: 1009,
    PUSH_GET_REWARDS: 1010,
    USER_FUBEN_CARD: 1011,
    MULTIFUBEN_SCENE_MEMBER_MOVE: 27001,
    MULTIFUBEN_SCENE_ENTER_NEXT_AREA: 27002,
    MULTIFUBEN_SCENE_ADD_PLAYER: 27003,
    MULTIFUBEN_SCENE_REMOVE_PLAYER: 27004,
  },
  MysteriousBusinessmanCmd: {
    CALL: 1,
    REFRESH: 2,
    BUY: 3,
  },
  NewYearCDKeyGiftCmd: {
    HAD_DRAWED: 1,
    DRAW_GIFT: 2,
  },
  NewYearCmd: {
    NEWYEAR_ENTER_CHRISTMAS: 1,
    NEWYEAR_BUY_CHRISTMASGOOD: 2,
    ENTER_NEW_LOTTERY: 3,
    DECORATION_NEW_LOTTERY: 4,
    REWARD_NEW_LOTTERY: 5,
    NEWYEAR_ENTER_HORSE: 6,
    NEWYEAR_ROCK_HORSE: 7,
    NEWYEAR_BUY_HORSE: 8,
  },
  NewYearFightCmd: {
    ENTER_SCENE: 1,
    LEFT_SCENE: 2,
    CREATE_TEAM: 3,
    JOIN_TEAM: 4,
    LEFT_TEAM: 5,
    KICK_MEMBER: 6,
    APPLY_LEADER: 7,
    HANDLE_APPLY_LEADER: 8,
    INVITE_MEMBER: 9,
    HANDLE_INVITE_MEMBER: 10,
    GET_MULTIFUBEN_INVITEVO_LIST: 11,
    MEMBER_PREPARED: 12,
    GET_TEAM_LIST: 13,
    TRANSFER_LEADER: 14,
    SEARCH_TEAM: 15,
    DRAW_REWARD: 16,
    PUSH_TEAM_CHANGES: 17,
    PUSH_INVITE_INFO: 18,
    PUSH_MEMBER_PREPARED: 19,
    BUY_RANDOM_COUNT: 99,
    RANDOM_ARMY: 100,
    CHANGE_MONSTER: 101,
    START: 102,
    NEWYEAR_MEMBER_MOVE: 103,
    PUSH_TEAMVO: 1101,
    PUSH_FIGHT_RESULT: 1102,
    NEWYEAR_PUSH_MEMBER_MOVE: 1103,
    NEWYEAR_PUSH_PLAYER_ENTER: 1104,
    NEWYEAR_PUSH_PLAYER_LEFT: 1105,
  },
  NewYearFortuneCmd: {
    NEWYEAR_FORTUNE_VIEW: 1,
    NEWYEAR_FORTUNE_BRUSH: 2,
    NEWYEAR_FORTUNE_IN_BOX: 3,
    NEWYEAR_FORTUNE_OUT_BOX: 4,
    NEWYEAR_FORTUNE_TAKE_OUT: 5,
    NEWYEAR_FORTUNE_REWARD: 6,
  },
  NotLoginGiftCmd: {
    CHECK_IS_RECEIVED: 1,
    RECEIVE_GIFT: 2,
  },
  OpenActivityCmd: {
    OPEN_ACTIVITY_VIEW: 1,
    REWARD_OPEN_ACTIVITY: 2,
    HAVE_REWARD_STATE: 3,
  },
  PassionPartCmd: {
    ENTER: 1,
    ENTER_SVR: 2,
    VOTE: 3,
    MATCH_REWARD: 4,
    EXCHANGE: 5,
    SVR_REWARD: 6,
  },
  PetCmd: {
    CURR_USERPETS: 1,
    CHANGE_CURR_USERPET: 2,
    UP_PET_LEVEL: 3,
    FLLOW_PET: 4,
    EXCHANGE_PEARLS: 6,
    UP_PEARL: 7,
    DOWN_PEARL: 8,
    COMBINE_PEARL: 9,
    COMBINE_SELECT_PEARL: 10,
    BUY_PEARL_CELLS: 12,
    GET_USER_PEARL_LIST_OF_ALL_PETS: 13,
    DIVEINE_PEARL: 14,
    DIVEINE_FULL_PEARL: 15,
    ADD_USER_PEARL: 17,
    ADD_ALL_USER_PEARL: 18,
    SELL_USER_PEARL: 19,
    SELL_SELECT_USER_PEARL: 20,
    LOCK_USER_PEARL: 21,
    UNLOCK_USER_PEARL: 22,
    CLEAR_COOL_TIME: 23,
    SUMMON_PET_PEARL: 24,
    SET_PET_PEARL: 25,
    SWAP_SELL_GREEN: 26,
    SWAP_ADD_AND_COMBINE_PEARL: 27,
    FUHUA: 28,
    BUY_LONG_PO: 29,
    CHANGE_TO_RED_PET_PEARL: 30,
    USE_RED_PEARL_GOD_POWER_ITEM: 31,
    BUY_POWER_PET_PEARL: 32,
    PET_PEARL_CONVERT: 33,
    GET_USER_PETPROFILE_LIST: 101,
    UNLOCK_PETPROFILE: 102,
    USE_PETPROFILE: 103,
    CANCELPETPROFILE: 104,
    GET_PETPROFILE_ABILITY: 105,
    TRAIN_PET_PROFILE_ATTR: 106,
    RENAME_PET_PROFILE: 107,
    PET_USE_ITEM: 108,
    AUTO_TRAIN_PET_PROFILE_ATTR: 109,
    POTENTIAL_PROMOTE: 121,
    POTENTIAL_UPSTAR: 122,
    RECOVERY_ENTER: 131,
    RECOVERY_ITEM: 132,
    PUSH_DROP_PET: 1016,
  },
  PlayerSkillCmd: {
    GET_PLAY_SKILL: 1,
    LEARN_SKILL: 2,
    EQUIP_SKILL: 3,
    CHANGE_SKILL_SETTING: 4,
  },
  PrankCmd: {
    ENTER_PRANK: 1,
    GET_FRIENDS: 2,
    GET_ALLIANCE_FRIENDS: 3,
    SEND_PRANK: 4,
    HAD_PRANK: 5,
    BUY_KEY: 6,
    GET_PRIZE_BOXS: 7,
    RECEIVE_PRIZE_BOX: 8,
    RECEIVE_PRIZE_BOXS: 9,
    OPEN_PRIZE_BOXS: 10,
    PUSH_NEW_PRIZE_BOX: 11,
    RECEIVE_PET_CARD: 12,
  },
  PrankDayCDKeyGiftCmd: {
    PRNAK_HAD_DRAWED: 1,
    PRANK_DRAW_GIFT: 2,
  },
  PullbackActivityCmd: {
    PULLBACK_ACTIVITY_VIEW: 1,
    PULLBACK_ACTIVITY_GIFT: 2,
  },
  QQMgrSignCmd: {
    QQMGRSIGN_GET_HISTORY: 1,
    QQMGRSIGN_REWARD: 2,
  },
  QTCmd: {
    USER_DATA: 1,
    SIGIN: 2,
    REWARD: 3,
  },
  QiXiCmd: {
    CREATE_TIME: 1,
    INVITE: 2,
    HANDLE_INVITE: 3,
    LEFT_TEAM: 4,
    KICK_MEMBER: 5,
    QIXI_CHALLENGE: 6,
    QIXI_CLEAR_CD: 7,
    QIXI_REWARD: 8,
    ENTER: 10,
    BUILD_PIE_BRIDGE: 11,
    EXCHANGE_PROP: 12,
    DRAW_SERVER_REWARD: 13,
    DRAW_NODE_REWARD: 14,
    PUSH_INVITE_INFO: 101,
    PUSH_TEAM_CHANGES: 102,
    PUSH_CHALLENGE_MONSTER: 103,
  },
  QualifyingCmd: {
    QUALIFYING_ENTER: 1,
    QUALIFYING_REWARD_UPGRADE: 2,
    QUALIFYING_REWARD_DAILY: 3,
    QUALIFYING_HONOR_RANK: 4,
    QUALIFYING_HONOR_PLAYER: 5,
    QUALIFYING_CHALLENGE: 101,
    QUALIFYING_PUSH_MATCH_RESULT: 102,
  },
  QuestionCmd: {
    PUSH_START: 1,
    PUSH_QUESTION: 2,
    ANSWER: 3,
    PUSH_RANKING: 4,
    PUSH_RANKING_REWARD: 5,
    ENTER: 6,
    EXIT: 7,
    CHECK_STATUS: 8,
  },
  RankCmd: {
    GET_RANKING_LIST: 1,
    PUSH_YESTERDAY_RANKING: 1001,
  },
  RechargeActivitiesCmd: {
    ENTER_CHARGE_FEEDBACK: 1,
    OBTAIN_GIFT: 2,
    PUSH_OPEN: 3,
    ENTER_CONSUME_FEEDBACK: 4,
    OBTAIN_CONSEMEGIFT: 5,
    PUSH_CONSUMECHANGE: 6,
  },
  RenewLotteryCmd: {
    GET_AWARD_LIST: 1,
    GET_FREE_AWARD: 2,
    DRAW: 3,
    TAKE_TO_BACKPACK: 4,
    WANT_HINT: 5,
    PUSH_YELLOW_AWARD: 6,
    PUSH_BLUE_AWARD: 7,
    PUSH_QQMEMBER_AWARD: 9,
    GET_HIGHEST_ITEM: 10,
    YELLOW_PROMPT: 11,
    SET_YELLOW_RENEW_PROMPT: 12,
    GET_TOKEN: 13,
    EXCHANGE_TOKEN: 14,
    PUSH_YELLOW_RENEW_REWARD: 1001,
  },
  ResistBugCmd: {
    ENTER_SCENE: 1,
    LEFT_SCENE: 2,
    CREATE_TEAM: 3,
    LEFT_TEAM: 4,
    JOIN_TEAM: 5,
    INVITE_MEMBER: 6,
    HANDLE_INVITE_MEMBER: 7,
    KICK_MEMBER: 8,
    APPLY_LEADER: 9,
    HANDLE_APPLY_LEADER: 10,
    QUICK_JOIN_TEAM: 11,
    MEMBER_PREPARED: 12,
    SET_AUTO_PREPARED: 13,
    START_RESIST: 14,
    RESIST_BUG: 15,
    GET_MY_TEAM_INFO: 16,
    GET_TEAM_LIST: 17,
    CHANGE_TEAM_PASSWD: 18,
    END_AT_ONCE: 19,
    GET_INVITEVO_LIST: 20,
    APPOINT_LEADER: 21,
    RESIST_STATUS: 22,
    PUSH_RESISTBUG_INFO: 1001,
    PUSH_TEAM_CHANGES: 1002,
    PUSH_INVITE_INFO: 1003,
    PUSH_MEMBER_PREPARED: 1004,
    PUSH_RESIST_INFO: 1005,
    PUSH_RESIST_RESULT: 1006,
    PUSH_RESIST_TURN_ROUND_INFO: 1007,
    PUSH_RESIST_END: 1008,
  },
  ResistBugExchangeCmd: {
    ENTER_PARY: 1,
    BUY_CLOBER: 2,
    PRAY: 3,
    EXCHANGE: 4,
  },
  RetrieveExpCmd: {
    STATUS: 1,
    INFO: 2,
    RETRIEVE: 3,
  },
  RockFightCmd: {
    COLSE_TEAM_LIST_VIEW: 1,
    CREATE_TEAM: 2,
    SORT_MEMBER: 4,
    LEFT_TEAM: 5,
    KICK_MEMBER: 6,
    APPLY_LEADER: 7,
    ANSWER_APPLY_LEADER: 8,
    INVITE_MEMBER: 9,
    ANSWER_INVITE_MEMBER: 10,
    GET_TEAM_LIST: 11,
    GET_INVITABLE_LIST: 12,
    QUERY_TEAM: 13,
    CLAIM_LEADER_WITHOUT_NO_ANSWEER: 14,
    TRANSFER_LEADER: 15,
    JOIN_TEAM: 16,
    QUERY_MY_TEAM: 17,
    PREPARE: 18,
    ROCK_OPPOSE: 101,
    USE_PROFIT: 103,
    BUFF: 104,
    START_FIGHT: 105,
    BUY_ROCK_COUNT: 106,
    BUFF_OPPOSE_TEAM: 107,
    LOCK_OPPOSE: 108,
    PUSH_TEAM_CHANGES_TO_MEMBER: 1001,
    PUSH_FIGHT: 1002,
    PUSH_INVITED: 1003,
    PUSH_TEAM_CHANGES_TO_LIST_VIEWERS: 1004,
    PUSH_REPLACE_LEADER_REQUEST: 1005,
    PUSH_ANSWER_REPLACE_LEADER_REQUEST: 1006,
    PUSH_KICKED: 1007,
    PUSH_BUFF_OTHER: 1008,
    PUSH_PREPARE: 1009,
    PUSH_LOCK_OPPOSE: 1010,
    BATTLE_OVER: 67001,
  },
  S3366CDKeyGiftCmd: {
    HAD_DRAWED: 1,
    DRAW_GIFT: 2,
  },
  SceneCmd: {
    CONSOLE: 0,
    SWITCH_CITY: 1,
    MOVE: 2,
    ENTER_SCENE: 3,
    LEFT_SCENE: 4,
    CLOSE_MOVE: 5,
    OPEN_MOVE: 6,
    SUSPEND_SCENE: 7,
    NOTIFY_SCENE: 8,
    FLYING_PICK_ITEM: 401,
    FLYING_QUERY_FLYING: 402,
    FLYING_TASK_PART: 403,
    PUSH_MOVE: 1001,
    PUSH_ENTER_SENCE: 1002,
    PUSH_LEFT_SENCE: 1003,
    PUSH_WING_INFO: 1004,
    PUSH_SCENE_RESIZE: 1005,
    PUSH_RUNNING_PET: 1006,
    CREATE_ALL_OTHER_PLAYER: 1701,
    ADD_OTHER_PLAYER: 1702,
    REMOVE_OTHER_PLAYER: 1703,
    UPDATE_OTHER_PLAYER_POS: 1704,
    SHOW_MAP_DISPLAY_OBJECT: 1705,
    UPDATE_OTHER_PLAYER_WING_INFO: 1706,
    SHOW_OTHER_PLAYER: 1707,
    CHANGE_SCENE_PLAYER_NUM: 1708,
    PLAYER_DEAD: 1709,
    UPDATE_OTHER_PLAYER_PET_FOLLOW_INFO: 1710,
    SET_TASK_FINISH_ROLE_POS: 1711,
    ACTIVE_MY_ROLE_WING: 1713,
    SNAP_SHOT_MAP_PICTURE: 1714,
    SHOW_BUBBLE_TEXT: 1715,
    CITY_PUSH_IS_AUTO_RUN: 1716,
    SCENE_CHANGE_MYROLE: 5001,
    MARRY_ENTER_SCENE: 8101,
    MARRY_CREAT_ONE_CLIP: 8102,
    MARRY_UPDATA_MOVEING: 8103,
    MARRY_REMOVE_ONE_CLIP: 8104,
    MARRY_STAR_ACTIVE: 8105,
    MARRY_PUSH_BLESS: 8106,
    MARRY_PUSH_SCENSE_WEDDING_TRIP: 8107,
    MARRY_PUSH_REMOVE_SCENSE_WEDDING_TRIP: 8108,
    GET_STATUE_INFO: 11601,
    CHRISTMAS_TREE_OPEN: 115002,
    CATCHBEAST_CLOSE_CATCHBEAST: 118002,
    CATCHBEAST_SWITCH_CATCHBEAST: 118004,
    CATCHBEAST_CLICK_MONSTER: 118005,
    CATCHBEAST_PUSH_MOVE: 118100,
    CATCHBEAST_PUSH_NEW_ROOM_USER: 118101,
    CATCHBEAST_PUSH_LEFT_ROOM: 118103,
    CATCHBEAST_PUSH_REFRESH_MONSTER: 118104,
    NEW_YEAR_TREE_OPEN: 119002,
    NEWYEARFIGHT_CLOSE_CATCHBEAST: 120002,
    NEWYEARFIGHT_PUSH_MOVE: 120100,
    NEWYEARFIGHT_PUSH_NEW_ROOM_USER: 120101,
    NEWYEARFIGHT_PUSH_LEFT_ROOM: 120103,
    KNOTTREE_CLOSE_CATCHBEAST: 121002,
    KNOTTREE_PUSH_MOVE: 121100,
    KNOTTREE_PUSH_NEW_ROOM_USER: 121101,
    KNOTTREE_PUSH_LEFT_ROOM: 121103,
    KNOTTREE_CLICK_MONSTER: 121104,
    KNOTTREE_PUSH_MARRIAGETREEVO: 121105,
    FLYING_PUSH_FLYING_STATUS: 401001,
    FLYING_PUSH_FLYING_DROP: 401002,
    FLYING_PUSH_FLYING_BEGIN: 401003,
    FLYING_PUSH_FLYING_FINISH: 401004,
    FLYING_PUSH_FLYING_MOVING: 401005,
    FLYING_PUSH_TIME_OUT: 401006,
    FLYING_EXIT: 401007,
    GYM_START_DO_GYM: 411001,
    GYM_FINISH_DO_GYM: 411002,
    CATCH_AUTO_RUN_TARGET_ACTION: 1180001,
  },
  SealCmd: {
    MY_SEAL: 1,
    UPGRADE: 2,
    LEARN_SKILL: 3,
    RESET: 4,
  },
  SeckillCmd: {
    OPEN_SECKILL_STORM_VIEW: 1,
    BUY_SECKILL_STORM_ITEM: 2,
    PUSH_SECKILL_STORM_OPEN: 100,
  },
  SevenFundCmd: {
    BUY_PLAN: 1,
    REWARD_PLAN: 2,
    QUERY_MONEY_PLAN: 3,
  },
  SevenPowerCmd: {
    GET_QISHENG_LIST: 1,
    USER_QISHENG: 2,
    QISHENG_CHANGE: 3,
  },
  ShrinePassesCmd: {
    GET_PASSES_STATUS: 1,
    ENTER_PASSES: 2,
    LEFT_PASSES: 3,
    GET_LAST_RANKING_LIST: 4,
    ATTACK_NPC: 5,
    PUSH_PASSES_STATUS: 1001,
    PUSH_ARMY_INFO: 1002,
    PUSH_USER_CHANGES: 1003,
    PUSH_PASSES_REWARD: 1004,
    PUSH_RANKING: 1005,
  },
  SinglesDayCmd: {
    SINGLES_DAY_ENTER: 1,
    SINGLES_DAY_CALL: 2,
    SINGLES_DAY_REWARD: 3,
    SINGLES_DAY_EXCHANGE: 4,
    SINGLES_DAY_SRVREWARD: 5,
  },
  SoulPalaceCmd: {
    ENTER_SOULPALACE: 1,
    BUY_SOULPALACE: 2,
    DRAW_REWARD_SOULPALACE: 3,
    UN_LOCK_SOULPALACE: 4,
    Refine_SOULPALACE: 5,
    ENTER_AREA_SOULPALACE: 6,
    ATTACK_MONSTER_SOULPALACE: 7,
    BACK_HOME_SOULPALACE: 8,
    BATTLE_OVER: 157001,
  },
  StMarkCmd: {
    MARK_ENTER: 1,
    HOLY_VESTIGE_ACTIVATION: 2,
    COUNTERMARK_HOLY_VESTIGE: 3,
    HOLY_VESTIGE_INTENSIFY: 4,
    HOLY_VESTIGE_AWAKEN: 5,
    HOLY_VESTIGE_AWAKEN_REPLACE: 6,
    HOLY_VESTIGE_USER_ATTR: 7,
  },
  StationCmd: {
    QUERY_STATION: 1,
    REWARD_STATION: 2,
    PUSH_STATION_BECOME_REWARDABLE: 1001,
  },
  StatueCmd: {
    GET_STATUE_INFO: 1,
    REWARD_STATUE: 2,
    NOTICE_STATUE_CHANGE: 1000,
  },
  StormAwardsCmd: {
    ENTER_UPGRADE_REWARD: 201,
    GET_UPGRADE_REWARD: 202,
    ENTER_SUPPORT_REWARD: 203,
    GET_SUPPORT_REWARD: 204,
    GET_POINTS: 205,
    INTEGRAL_EXCHANGE: 206,
  },
  StrongGiftCmd: {
    PUSH_GIFT: 1,
    RECEIVE_GIFT: 2,
    GIFT_INFO: 3,
  },
  StrongestCmd: {
    GET_ACROSS_BATTLE: 101,
    GET_ACROSS_BATTLE_DETAIL: 103,
    GET_CHAMPION_LIST: 104,
    GET_BATTLE_REPORT: 105,
    ENTER_UPGRADE_REWARD: 201,
    GET_UPGRADE_REWARD: 202,
    ENTER_SUPPORT_REWARD: 203,
    GET_SUPPORT_REWARD: 204,
    PREVIOUS_KINGS_LIST: 207,
    HAVE_REWARD: 301,
    CHAMPION_SHOW: 302,
    EDIT_MESSAGE: 303,
    CHAMPION_GIFT: 305,
    STRONGEST_FLOWER: 306,
    STRONGEST_EGG: 307,
    STRONGEST_SUPPORT: 308,
    TEAM_BATTLE_INFO: 309,
    GET_STATUS: 311,
    STRONGEST_GET_MY_INFO: 312,
    GET_BATTLE_STATUS: 313,
    GET_STATUE_INFO: 314,
    REWARD_STATUE: 315,
    STRONGEST_UPDATE_FIGHT: 401,
    STRONGEST_CLEAR_UPDATE_FIGHT_CD: 402,
    STRONGEST_VIEW_PLAYER_DETAIL: 403,
    STRONGEST_VIEW_MY_DETAIL: 404,
    GET_MODIFY_STRONGESTVO: 406,
  },
  SuperBraveRebatesCmd: {
    CHECK_FIRST_COMEBACK_INFO: 1,
    DRAW_FIRST_COMEBACK_GIFT: 2,
  },
  TaskCmd: {
    QUERY_TASK_VIEW: 1,
    RECEIVE_TASK: 2,
    DROP_TASK: 3,
    FINISH_TASK: 4,
    REWARD_TASK: 5,
    RECORD_TASK_NOTE: 6,
    FETCH_TASK_NOTE: 7,
    REWARD_GUIDER: 8,
    QUERY_TASK_STATUS: 9,
    SAVE_TASK_STEP: 10,
    REWARD_DAILY_TASK: 11,
    REWARD_VIP_TASK: 12,
    RECEIVE_CYCLE_TASK: 13,
    REWARD_CYCLE_TASK: 14,
    QUERY_CYCLE_TASK: 15,
    DROP_CYCLE_TASK: 16,
    RAISE_TASK_EVENT: 17,
    WISH: 18,
    QUERY_WISH: 19,
    REWARD_TIMED_TASK: 20,
    REWARD_ABILITY_TASK: 21,
    PUSH_REFRESH_TASK: 1001,
    PUSH_TASK_CHANGED: 1002,
    PUSH_DAILY_TASK: 1003,
    PUSH_VIP_TASK: 1004,
    PUSH_CYCLE_TASK: 1005,
    PUSH_TASK_RESULT: 1006,
    PUSH_TIMED_TASK: 1007,
  },
  TecentCmd: {
    SET_TECENT_PARAMETER: 1,
    REWARD_PF_LX_LOGIN: 2,
    REWARD_GOLD_COUPON_GIFT: 3,
    REWARD_PHONE_CDKEY: 4,
    REWARD_CAIBEI: 5,
    REWARD_PCU_GIFT: 6,
    QUERY_PCU_GIFT: 7,
    CHECK_ONPANEL_IS_RECEIVED: 12,
    RECEIVE_ONPANEL_GIFT: 13,
    PUSH_REWARD_PF_LX_LOGIN_RESULT: 1001,
    PUSH_TECENT_PARAMETER_LOST: 1002,
    PUSH_TECENT_PHONE_CDKEY: 1003,
    PUSH_CAIBEI_REWARD_RESULT: 1004,
    PUSH_PCUGIFT_RESULT: 1005,
  },
  ThousandSrvCmd: {
    THOUSAND_SRV_VIEW: 1,
    THOUSAND_SRV_CLAP: 2,
    THOUSAND_SRV_REWARD: 3,
    THOUSAND_SRV_FIGHT: 4,
    THOUSAND_SRV_PUSH_BOSS_HP: 1000,
    THOUSAND_SRV_PUSH_BOSS_OPEN: 1002,
  },
  TianQiCmd: {
    ENTER_SCENE: 1,
    LEFT_SCENE: 2,
    CREATE_TEAM: 3,
    JOIN_TEAM: 4,
    LEFT_TEAM: 5,
    KICK_MEMBER: 6,
    APPLY_LEADER: 7,
    HANDLE_APPLY_LEADER: 8,
    INVITE_MEMBER: 9,
    HANDLE_INVITE_MEMBER: 10,
    GET_MY_TEAM_INFO: 11,
    GET_MULTIFUBEN_TEAM_LIST: 12,
    GET_MULTIFUBEN_INVITEVO_LIST: 13,
    START_FUBEN: 14,
    MEMBER_PREPARED: 15,
    SET_AUTO_PREPARED: 16,
    SEND_INVITATION: 17,
    JOIN_TEAM_BY_INVITATION: 18,
    TRANSFER_LEADER: 19,
    CHANGE_FUBEN: 20,
    CHANGE_TEAM_PASSWD: 21,
    ENTRY_AREA: 100,
    ATTACK_NPC: 101,
    REFRESH_TEAM: 102,
    MEMBER_MOVE: 103,
    SET_AUTO_ATTACK: 104,
    PUSH_START_FUBEN: 1001,
    PUSH_TEAM_CHANGES: 1003,
    PUSH_INVITE_INFO: 1004,
    PUSH_MEMBER_PREPARED: 1005,
    PUSH_MEMBER_MOVE: 1006,
    PUSH_SEND_INVITATION: 1007,
    PUSH_WAR_SCENE_INFO: 1101,
    PUSH_WAR_ARMY_INFO: 1102,
    PUSH_WAR_NEXT_AREA_INFO: 1103,
    PUSH_WAR_END: 1104,
    ATTACK_MONSTER_BATTLE_OVER: 14601,
    TIAN_QI_SCENE_MEMBER_MOVE: 14602,
    TIAN_QI_SCENE_REMOVE_PLAYER: 14603,
    TIAN_QI_SCENE_CHANGE: 14604,
    TIAN_QI_MONSTER_CREATE: 14605,
    TIAN_QI_MONSTER_CHANGE: 14606,
    TIAN_QI_CITY_CHANGE: 14607,
    TIAN_QI_ROUND_OVER: 14608,
    TIAN_QI_OVER: 14609,
    TIAN_QI_AUTO_ATTACK: 14610,
  },
  TopDuelCmd: {
    ENTER_CRAZY_BATTLE: 1,
    ATTACK: 2,
    REWARD_LAYER: 3,
    RESET: 4,
    RESTART: 5,
    GET_STATE: 6,
    PUSH_CRAZY_BATTLE_STATE: 1001,
  },
  TopUpActivitiesCmd: {
    TOP_UP_ACTIVITIES_VIEW: 1,
    TOP_UP_ACTIVITIES_GIFT: 2,
    PUSH_OPEN: 3,
    TOP_UP_ACTIVITIES_GET_SEND_LIST: 4,
    TOP_UP_ACTIVITIES_SEND_GIFT: 5,
  },
  TowerCmd: {
    QUERY_MY_TOWER: 1,
    QUERY_DROPS: 2,
    QUERY_RANK: 3,
    QUERY_STELE: 4,
    ATTACK_LAYER: 5,
    REVIVE: 6,
    RESET: 7,
    REWARD_STELE: 8,
    REWARD_LAYER_BOX: 9,
    VIEW_FIGHT: 10,
    BUY_SHOP: 11,
    START_PROCESS: 12,
    ENTER_NEXT_LAYER: 13,
    TOWER_ITEM_REVIVE: 14,
    AUTO_CLIMB_TOWER: 29002,
    BATTLE_OVER: 29003,
  },
  TravelActCmd: {
    GET_USERTRAVEL: 1,
    REFRESH_FIGHT: 2,
    FIGHT: 3,
    INVITE: 4,
    RE_INVITE: 5,
    DO_TRAVEL: 6,
    LEFT_TRAVEL: 7,
    BUY_TICKET: 8,
    BUY_SHOP: 9,
    GET_INVITE_LIST: 10,
    COOL_TIME: 11,
    CREATE_TEAM: 12,
    PUSH_INVITE: 1001,
    PUSH_RE_INVITE: 1002,
    PUSH_TRAVEL_ACT: 1003,
    PUSH_LEFT_TRAVEL: 1004,
  },
  TravelTraderCmd: {
    GET_USERFLEAMARKETVO: 1,
    BUY_SHOP: 2,
  },
  UnityPowerCmd: {
    BUY_UNITY_POWER_ITEM: 11,
    GET_UNITY_POWER_VALUE: 12,
    PUSH_UNITY_POWER: 110,
  },
  UserInfoCmd: {
    REWARDVO_REQUEST: -3,
    COPY_PLAYER: -1,
    GET_SERVER_TIME: 0,
    LOGIN: 1,
    CHECK_USER: 2,
    CREATE_PLAYER: 3,
    OFFLINE_RECONNECT: 4,
    ALTERNATE_FCM: 5,
    VIEW_PLAYER_INFO: 6,
    GET_USER_ATTRIBUTE: 7,
    BUY_COIN: 8,
    BUY_ENERGY: 9,
    SELECT_NATION: 10,
    BUY_PACK: 11,
    GET_RECOMMEND_NATION: 12,
    RENAME: 13,
    SETAUTOBUYCOIN: 14,
    AUTOBUYCOIN: 15,
    GET_USER_ATTR: 17,
    QUERY_USER_FLAG: 18,
    QUERY_OPEN: 19,
    QUERY_USER_TENCENT_INFO: 20,
    GET_EXP_PILL_INFO: 21,
    USE_DOUBLE_EXP_PILL: 22,
    USE_EXP_PILL: 23,
    GET_ABILITY_DETAIL: 25,
    OPEN_LEVELUP: 26,
    SHEMALE: 27,
    INFORM_TIME_EXPIRE: 28,
    GET_USER_COUNT: 29,
    NOTIFY_XILIANOPEN: 30,
    LEVEL_UPGRADE_ITEM: 31,
    CRIT_BUFF_INFO: 32,
    COPY_FIGHT_REPORT: 1000,
    PUSH_OFF_LINE: 1001,
    PUSH_REWARD_VO: 1002,
    PUSH_MONEY_VO: 1003,
    CLEAR_ANONYMOUS_SESSION: 1004,
    PUSH_CHARGE: 1006,
    PUSH_VIP: 1007,
    PUSH_OPEN: 1008,
    PUSH_CONSUME: 1009,
    PUSH_TIME_EXPIRES: 1010,
    CONNECT_OK: 1097,
    CONNECT_SERVER: 1098,
    USER_PUSH_INCOME: 10010,
    GET_INCOME: 10011,
  },
  UserItemCmd: {
    USEITEM: 1,
    SALEITEM: 2,
    GET_BAG_DATA_ITEM: 3,
    COMBINE_ITEM: 4,
    OPEN_ITEM_BOX: 5,
    GET_TEMPBAG: 7,
    TAK_ETEMPBAG: 8,
    GET_BUFFQUEUE: 9,
    DEL_BUFFQUEUE: 10,
    COMBINE_REFINE: 11,
    PUSH_BUFF_QUEUE: 1001,
  },
  ValentinesDayActivityCmd: {
    ValentinesDay_Enter: 1,
    ValentinesDay_PROFESS: 2,
    ValentinesDay_DRAW_PROFESS_REWARD: 3,
    ValentinesDay_DRAW_SERVER_REWARD: 4,
    ValentinesDay_LARGESS_CHOCOLATE: 5,
    ValentinesDay_DRAW_BLESSING: 6,
    ValentinesDay_PUSH_HEART_INFO: 7,
  },
  VipCmd: {
    REWARD_VIP_COUPON: 1,
    REWARD_VIP_GIFT: 2,
    USE_ITEM_VIP_ITEM: 3,
    USE_VIP_GROW_ITEM: 4,
    FINISH_TEMP_VIP: 5,
    PUSH_VIP: 1001,
    PUSH_VIP_GROW_VALUE: 1002,
  },
  VowCmd: {
    ENTER_VOW: 1,
    VOW: 2,
    EXCHANGE: 3,
    PUSH_AWARDVOS: 4,
  },
  WeChatGiftCmd: {
    WECHAT_CHECK_IS_RECEIVED: 1,
    WECHAT_RECEIVE_GIFT: 2,
  },
  WorldCapCmd: {
    ENTER: 1,
    CHANGE_COUNTRY: 2,
    AUTO_CHANGE_COUNTRY: 3,
    GOAL: 4,
    DEADLY_GOAL: 5,
    REWARD_EXCHANGE: 6,
    REFRESH_SRV_REWARD: 7,
    SRV_REWARD: 8,
  },
  WorldCupHotCmd: {
    WORLD_CUP_HOT_ENTER: 1,
    WORLD_CUP_HOT_SHOOT: 2,
    WORLD_CUP_HOT_REWARD: 3,
    WORLD_CUP_HOT_EXCHANGE: 4,
    WORLD_CUP_HOT_SRVREWARD: 5,
  },
  WrathDragonCmd: {
    GET_MY_INFO: 1,
    BUY_ATTACK_TIMES: 2,
    CLEAN_CD: 3,
    ATTACK: 4,
    GET_TOP_RANKING: 5,
    EXCHANGE: 6,
    CHECK_DAILY_REWARD: 7,
    BUY_DAILY_REWARD: 8,
    GET_YESTODAY_RANKING: 9,
    REWARD_BOX: 10,
    BUY_SCORE: 11,
    PUSH_YESTERDAY_RANKING: 1001,
    PUSH_OUT_OFF_RANKING: 1002,
  },
  WuYiCmd: {
    WUYI_VIEW: 1,
    WUYI_ROCK: 2,
    WUYI_REWARD: 3,
    WUYI_SRVREWARD: 4,
  },
  YellowCmd: {
    QUEYR_USER_YELLOW: 1,
    REWARD_YELLOW_GIFT: 2,
    REWARD_3366: 3,
    REWARD_3366_DAILY_COST_GIFT: 4,
    BLUE_LOTTERY_ENTER: 5,
    BLUE_LOTTERY_GET: 6,
    BLUE_LOTTERY_BUY_COUNT: 7,
    PUSH_YELLOW_GIFT_RESULT: 1001,
    PUSH_3366_GIFT_RESULT: 1002,
    PUSH_3366_DAILY_COST_GIFT_RESULT: 1003,
  },
};
// ─── DESTINATIONS (modules serveur) ──────────────────────────────────────────
const DEST = {
  COMMONSYS  : 0,
  USER_INFO  : 1,
  SCENE      : 2,
  TASK       : 3,
  EQUIP      : 4,
  USER_ITEM  : 5,
  FRIEND     : 6,
  CHAT       : 7,
  ALLIANCE   : 8,
  FUBEN      : 9,
  FIGHT      : 10,
  PET        : 11,
  MALL       : 12,
  ARENA      : 13,
  TOWER      : 14,
  GIFT       : 15,
  VIP        : 16,
  RANK       : 17,
  EMAIL      : 18,
  MARKET     : 19,
  DIVINE     : 20,
  GYM        : 21,
  FARM       : 22,
  MULTIFUBEN : 23,
  DEVILDOM   : 24,
  MEDAL      : 25,
  BALANCE    : 100,
};

// ─── ÉTAT GLOBAL ──────────────────────────────────────────────────────────────
const players    = new Map();   // id -> Player
const scenes     = new Map();   // sceneId -> Set<playerId>
let   nextId     = 1;

// ─── FORMAT PAQUET ────────────────────────────────────────────────────────────
// Entête: [4 bytes MAGIC][4 bytes payload_length]
// Payload: [8 bytes double timestamp][4 bytes dest][4 bytes cmd][JSON data]
const MAGIC = 0xDEADBEEF;

function parsePacket(buf) {
  if (buf.length < 8) return null;
  const magic = buf.readUInt32BE(0);
  const plen  = buf.readUInt32BE(4);
  if (buf.length < 8 + plen) return null;
  const payload  = buf.slice(8, 8 + plen);
  return { magic, payload, consumed: 8 + plen };
}

function parsePayload(payload) {
  try {
    if (payload.length < 16) return null;
    const timestamp = payload.readDoubleBE(0);   // 8 bytes
    const dest      = payload.readInt32BE(8);     // 4 bytes
    const cmd       = payload.readInt32BE(12);    // 4 bytes
    let   data      = {};
    if (payload.length > 16) {
      const jsonStr = payload.slice(16).toString('utf8').replace(/\0/g, '').trim();
      if (jsonStr.startsWith('{')) data = JSON.parse(jsonStr);
    }
    return { timestamp, dest, cmd, data };
  } catch(e) {
    return null;
  }
}

function buildPacket(dest, cmd, data = {}) {
  const jsonBuf  = Buffer.from(JSON.stringify(data), 'utf8');
  const payLen   = 16 + jsonBuf.length;
  const buf      = Buffer.alloc(8 + payLen);
  buf.writeUInt32BE(MAGIC, 0);
  buf.writeUInt32BE(payLen, 4);
  buf.writeDoubleBE(Date.now() / 1000, 8);
  buf.writeInt32BE(dest, 16);
  buf.writeInt32BE(cmd, 20);
  jsonBuf.copy(buf, 24);
  return buf;
}

function sendTo(player, dest, cmd, data = {}) {
  try { player.socket.write(buildPacket(dest, cmd, data)); }
  catch(e) { /* socket fermée */ }
}

function broadcast(dest, cmd, data = {}, excludeId = null) {
  const pkt = buildPacket(dest, cmd, data);
  players.forEach((p, id) => {
    if (id !== excludeId) try { p.socket.write(pkt); } catch(e) {}
  });
}

function broadcastScene(sceneId, dest, cmd, data = {}, excludeId = null) {
  const set = scenes.get(sceneId);
  if (!set) return;
  const pkt = buildPacket(dest, cmd, data);
  set.forEach(id => {
    if (id === excludeId) return;
    const p = players.get(id);
    if (p) try { p.socket.write(pkt); } catch(e) {}
  });
}

// ─── HANDLERS ─────────────────────────────────────────────────────────────────

// ── UserInfo ──────────────────────────────────────────────────────────────────
async function handleUserInfo(player, cmd, data) {
  switch (cmd) {

    case OPCODES.UserInfoCmd.GET_SERVER_TIME:
      return { ok: true, serverTime: Date.now(), dest: DEST.USER_INFO, cmd };

    case OPCODES.UserInfoCmd.LOGIN: {
      const { accountId, token } = data;
      const { data: compte, error } = await supabase
        .from('comptes').select('*').eq('id', accountId).single();
      if (error || !compte) return { ok: false, msg: 'Compte introuvable' };
      const { data: perso } = await supabase
        .from('personnages').select('*').eq('compte_id', accountId).single();
      player.accountId = accountId;
      player.perso     = perso;
      console.log(`[LOGIN] ${perso?.nom || '?'} (id=${accountId})`);
      return {
        ok: true,
        cmd: OPCODES.UserInfoCmd.CONNECT_OK,
        playerData: perso,
        serverTime: Date.now(),
      };
    }

    case OPCODES.UserInfoCmd.CREATE_PLAYER: {
      const { nom, classeId, classeNom, classeEmoji } = data;
      const { data: exist } = await supabase
        .from('personnages').select('id').eq('nom', nom).single();
      if (exist) return { ok: false, msg: 'Nom déjà pris' };
      const { data: perso, error } = await supabase.from('personnages').insert({
        compte_id: player.accountId, nom,
        classe_id: classeId, classe_nom: classeNom, classe_emoji: classeEmoji,
        niveau: 1, xp: 0, xp_max: 1000,
        hp: 1000, hp_max: 1000, mp: 500, mp_max: 500,
        or_joueur: 5000, yuanbao: 100, puissance: 5000, vip: 0, guilde: '',
      }).select().single();
      if (error) return { ok: false, msg: error.message };
      player.perso = perso;
      return { ok: true, playerData: perso };
    }

    case OPCODES.UserInfoCmd.VIEW_PLAYER_INFO: {
      const { data: perso } = await supabase
        .from('personnages').select('*').eq('compte_id', data.userId).single();
      return { ok: true, playerData: perso };
    }

    case OPCODES.UserInfoCmd.GET_USER_ATTRIBUTE:
    case OPCODES.UserInfoCmd.GET_USER_ATTR:
      return { ok: true, attrs: player.perso || {} };

    case OPCODES.UserInfoCmd.BUY_COIN: {
      const newYuanbao = (player.perso?.yuanbao || 0) + (data.amount || 0);
      await supabase.from('personnages').update({ yuanbao: newYuanbao })
        .eq('compte_id', player.accountId);
      if (player.perso) player.perso.yuanbao = newYuanbao;
      return { ok: true, yuanbao: newYuanbao };
    }

    default:
      return null;
  }
}

// ── Chat ──────────────────────────────────────────────────────────────────────
async function handleChat(player, cmd, data) {
  switch (cmd) {

    case OPCODES.ChatCmd.SEND_CHAT_MESSAGE: {
      const msg = String(data.message || '').slice(0, 200);
      const nom = player.perso?.nom || 'Inconnu';
      const emoji = player.perso?.classe_emoji || '⚔️';
      await supabase.from('chat_monde').insert({ nom_joueur: nom, classe_emoji: emoji, message: msg });
      broadcast(DEST.CHAT, OPCODES.ChatCmd.CHAT_PUSH, { sender: nom, emoji, message: msg, channel: data.channel || 1 });
      return { ok: true };
    }

    case OPCODES.ChatCmd.CHAT_NOTICE:
      broadcast(DEST.CHAT, OPCODES.ChatCmd.CHAT_NOTICE, { message: data.message });
      return { ok: true };

    default:
      return null;
  }
}

// ── Scene ─────────────────────────────────────────────────────────────────────
async function handleScene(player, cmd, data) {
  switch (cmd) {

    case OPCODES.SceneCmd.ENTER_SCENE: {
      const sceneId = data.sceneId || 'village';
      player.sceneId = sceneId;
      player.x = data.x || 0;
      player.y = data.y || 0;
      if (!scenes.has(sceneId)) scenes.set(sceneId, new Set());
      scenes.get(sceneId).add(player.id);
      // Notifier les autres
      broadcastScene(sceneId, DEST.SCENE, OPCODES.SceneCmd.PUSH_ENTER_SENCE, {
        playerId: player.id, nom: player.perso?.nom, classeEmoji: player.perso?.classe_emoji,
        x: player.x, y: player.y,
      }, player.id);
      // Envoyer la liste des joueurs présents
      const present = [];
      scenes.get(sceneId).forEach(id => {
        const p = players.get(id);
        if (p && p.id !== player.id) present.push({ id: p.id, nom: p.perso?.nom, x: p.x, y: p.y });
      });
      return { ok: true, sceneId, players: present };
    }

    case OPCODES.SceneCmd.LEFT_SCENE: {
      if (player.sceneId) {
        const set = scenes.get(player.sceneId);
        if (set) set.delete(player.id);
        broadcastScene(player.sceneId, DEST.SCENE, OPCODES.SceneCmd.PUSH_LEFT_SENCE, {
          playerId: player.id,
        });
        player.sceneId = null;
      }
      return { ok: true };
    }

    case OPCODES.SceneCmd.MOVE: {
      player.x = data.x;
      player.y = data.y;
      broadcastScene(player.sceneId, DEST.SCENE, OPCODES.SceneCmd.PUSH_MOVE, {
        playerId: player.id, x: data.x, y: data.y,
      }, player.id);
      return null; // pas de réponse au sender
    }

    case OPCODES.SceneCmd.SWITCH_CITY:
      return { ok: true, cityId: data.cityId };

    default:
      return null;
  }
}

// ── Task ──────────────────────────────────────────────────────────────────────
async function handleTask(player, cmd, data) {
  switch (cmd) {
    case OPCODES.TaskCmd.QUERY_TASK_VIEW:
      return { ok: true, tasks: [] };
    case OPCODES.TaskCmd.RECEIVE_TASK:
      return { ok: true, taskId: data.taskId };
    case OPCODES.TaskCmd.FINISH_TASK:
      return { ok: true, taskId: data.taskId };
    case OPCODES.TaskCmd.REWARD_TASK:
      return { ok: true, rewards: [] };
    case OPCODES.TaskCmd.QUERY_TASK_STATUS:
      return { ok: true, status: [] };
    default:
      return null;
  }
}

// ── Equip ─────────────────────────────────────────────────────────────────────
async function handleEquip(player, cmd, data) {
  switch (cmd) {
    case OPCODES.EquipCmd.WEAR:
      return { ok: true, slot: data.slot, equipId: data.equipId };
    case OPCODES.EquipCmd.UPSTAR:
      return { ok: true, newStar: (data.currentStar || 0) + 1 };
    case OPCODES.EquipCmd.FORGE:
      return { ok: true };
    case OPCODES.EquipCmd.SHOW_USEREQUIP:
      return { ok: true, equips: [] };
    default:
      return null;
  }
}

// ── UserItem (Inventaire) ─────────────────────────────────────────────────────
async function handleUserItem(player, cmd, data) {
  switch (cmd) {
    case OPCODES.UserItemCmd.GET_BAG_DATA_ITEM: {
      const { data: items } = await supabase.from('inventaires')
        .select('*').eq('compte_id', player.accountId);
      return { ok: true, items: items || [] };
    }
    case OPCODES.UserItemCmd.USEITEM:
      return { ok: true, itemId: data.itemId };
    case OPCODES.UserItemCmd.SALEITEM: {
      const { error } = await supabase.from('inventaires')
        .delete().eq('id', data.itemId);
      return { ok: !error };
    }
    case OPCODES.UserItemCmd.COMBINE_ITEM:
      return { ok: true };
    case OPCODES.UserItemCmd.OPEN_ITEM_BOX:
      return { ok: true, rewards: [] };
    default:
      return null;
  }
}

// ── Friend ────────────────────────────────────────────────────────────────────
async function handleFriend(player, cmd, data) {
  switch (cmd) {
    case OPCODES.FriendCmd.FRIEND_GETFRIEND:
      return { ok: true, friends: [] };
    case OPCODES.FriendCmd.FRIEND_ADDFRIEND:
      return { ok: true };
    case OPCODES.FriendCmd.FRIEND_DELETEFRIEND:
      return { ok: true };
    case OPCODES.FriendCmd.ISONLINE: {
      const online = [...players.values()].some(p => p.perso?.nom === data.nom);
      return { ok: true, online };
    }
    default:
      return null;
  }
}

// ── Alliance (Guilde) ─────────────────────────────────────────────────────────
async function handleAlliance(player, cmd, data) {
  switch (cmd) {
    case OPCODES.AllianceCmd.QUERY_MY_ALLIANCE:
      return { ok: true, alliance: player.perso?.guilde || null };
    case OPCODES.AllianceCmd.PAGE_ALLIANCE_LIST:
      return { ok: true, list: [] };
    case OPCODES.AllianceCmd.CREATE_ALLIANCE: {
      const { nom } = data;
      await supabase.from('personnages').update({ guilde: nom })
        .eq('compte_id', player.accountId);
      if (player.perso) player.perso.guilde = nom;
      return { ok: true, nom };
    }
    case OPCODES.AllianceCmd.APPLY_ALLIANCE:
      return { ok: true };
    case OPCODES.AllianceCmd.LEFT_ALLIANCE: {
      await supabase.from('personnages').update({ guilde: '' })
        .eq('compte_id', player.accountId);
      if (player.perso) player.perso.guilde = '';
      return { ok: true };
    }
    default:
      return null;
  }
}

// ── Fuben (Donjons) ───────────────────────────────────────────────────────────
async function handleFuben(player, cmd, data) {
  switch (cmd) {
    case OPCODES.FubenCmd.QEURY_FIRST_BREAK:
      return { ok: true, areas: [] };
    case OPCODES.FubenCmd.ENTER_SINGLE_AREA:
      return { ok: true, areaId: data.areaId, monsters: generateMonsters(data.areaId) };
    case OPCODES.FubenCmd.ATTACK_MONSTER: {
      const result = calcFubenCombat(player.perso, data);
      if (result.victoire) {
        const newXp  = Math.min(player.perso.xp_max, player.perso.xp + result.xpGagne);
        const newOr  = (player.perso.or_joueur || 0) + result.orGagne;
        const newPwr = (player.perso.puissance || 0) + Math.floor(result.xpGagne / 8);
        await supabase.from('personnages').update({ xp: newXp, or_joueur: newOr, puissance: newPwr })
          .eq('compte_id', player.accountId);
        if (player.perso) { player.perso.xp = newXp; player.perso.or_joueur = newOr; player.perso.puissance = newPwr; }
        await supabase.from('historique_combats').insert({
          nom_joueur: player.perso?.nom, donjon_nom: `Zone ${data.areaId}`,
          victoire: true, xp_gagne: result.xpGagne, or_gagne: result.orGagne,
        });
      }
      return { ok: true, ...result };
    }
    case OPCODES.FubenCmd.REWARD_AREA:
      return { ok: true, rewards: [] };
    case OPCODES.FubenCmd.BACK_HOME:
      return { ok: true };
    default:
      return null;
  }
}

// ── Fight (PvP) ───────────────────────────────────────────────────────────────
async function handleFight(player, cmd, data) {
  switch (cmd) {
    case OPCODES.FightCmd.GET_MY_FIGHT_INFO:
      return { ok: true, fightInfo: player.perso || {} };
    case OPCODES.FightCmd.REQUEST_FIGHT: {
      const target = [...players.values()].find(p => p.perso?.nom === data.targetNom);
      if (!target) return { ok: false, msg: 'Joueur introuvable' };
      sendTo(target, DEST.FIGHT, OPCODES.FightCmd.PUSH_REQUEST_FIGHT, {
        challenger: player.perso?.nom, challengerId: player.id,
      });
      return { ok: true };
    }
    case OPCODES.FightCmd.HANDLE_FIGHT_REQUEST: {
      const challenger = players.get(data.challengerId);
      if (!challenger) return { ok: false };
      const result = calcPvP(player.perso, challenger.perso);
      sendTo(challenger, DEST.FIGHT, OPCODES.FightCmd.PUSH_HANDLE_FIGHT_REQUEST, result);
      return { ok: true, ...result };
    }
    default:
      return null;
  }
}

// ── Arena ─────────────────────────────────────────────────────────────────────
async function handleArena(player, cmd, data) {
  switch (cmd) {
    case OPCODES.ArenaCmd.QUERY_ARENA_VIEW:
      return { ok: true, arenaInfo: { rank: 999, points: 0 } };
    case OPCODES.ArenaCmd.QUERY_OPPOSE_LIST: {
      const { data: opponents } = await supabase.from('personnages')
        .select('nom, classe_emoji, niveau, puissance')
        .order('puissance', { ascending: false }).limit(10);
      return { ok: true, opponents: opponents || [] };
    }
    case OPCODES.ArenaCmd.ATTACK: {
      const { data: target } = await supabase.from('personnages')
        .select('*').eq('nom', data.targetNom).single();
      const result = calcPvP(player.perso, target);
      return { ok: true, ...result };
    }
    case OPCODES.ArenaCmd.FETCH_RANK_LIST: {
      const { data: ranking } = await supabase.from('personnages')
        .select('nom, classe_emoji, classe_nom, niveau, puissance, guilde')
        .order('puissance', { ascending: false }).limit(50);
      return { ok: true, ranking: ranking || [] };
    }
    default:
      return null;
  }
}

// ── Tower (Tour) ──────────────────────────────────────────────────────────────
async function handleTower(player, cmd, data) {
  switch (cmd) {
    case OPCODES.TowerCmd.QUERY_MY_TOWER:
      return { ok: true, tower: { currentLayer: 1, maxLayer: 1 } };
    case OPCODES.TowerCmd.ATTACK_LAYER:
      return { ok: true, victoire: true, rewards: [] };
    case OPCODES.TowerCmd.QUERY_RANK:
      return { ok: true, rank: [] };
    default:
      return null;
  }
}

// ── Mall (Boutique) ───────────────────────────────────────────────────────────
async function handleMall(player, cmd, data) {
  switch (cmd) {
    case OPCODES.MallCmd.LIST_SHOPGOOD_ACTIVITY:
      return { ok: true, goods: [] };
    case OPCODES.MallCmd.BUY_ITEM: {
      const { itemId, price } = data;
      const or = player.perso?.or_joueur || 0;
      if (or < price) return { ok: false, msg: 'Pas assez d\'or' };
      const newOr = or - price;
      await supabase.from('personnages').update({ or_joueur: newOr })
        .eq('compte_id', player.accountId);
      await supabase.from('inventaires').insert({
        compte_id: player.accountId, nom_joueur: player.perso?.nom,
        item_id: itemId, item_nom: data.itemNom || 'Objet', item_icon: data.icon || '📦', item_qualite: 'Normal',
      });
      if (player.perso) player.perso.or_joueur = newOr;
      return { ok: true, newOr };
    }
    default:
      return null;
  }
}

// ── Gift ──────────────────────────────────────────────────────────────────────
async function handleGift(player, cmd, data) {
  switch (cmd) {
    case OPCODES.GiftCmd.LIST_BASE_GFIT:
      return { ok: true, gifts: [] };
    case OPCODES.GiftCmd.RECEIVE_GFIT:
      return { ok: true };
    case OPCODES.GiftCmd.RECEIVE_LOGIN_GIFT:
      return { ok: true, reward: { or: 500 } };
    default:
      return null;
  }
}

// ── VIP ───────────────────────────────────────────────────────────────────────
async function handleVip(player, cmd, data) {
  switch (cmd) {
    case OPCODES.VipCmd.REWARD_VIP_GIFT:
      return { ok: true };
    case OPCODES.VipCmd.REWARD_VIP_COUPON:
      return { ok: true };
    default:
      return null;
  }
}

// ── Rank ──────────────────────────────────────────────────────────────────────
async function handleRank(player, cmd, data) {
  switch (cmd) {
    case OPCODES.RankCmd.GET_RANKING_LIST: {
      const { data: ranking } = await supabase.from('personnages')
        .select('nom, classe_emoji, classe_nom, niveau, puissance, guilde')
        .order('puissance', { ascending: false }).limit(50);
      return { ok: true, ranking: ranking || [] };
    }
    default:
      return null;
  }
}

// ── Email ─────────────────────────────────────────────────────────────────────
async function handleEmail(player, cmd, data) {
  switch (cmd) {
    case OPCODES.EmailCmd.LIST_ALL_EMAILS:
      return { ok: true, emails: [] };
    case OPCODES.EmailCmd.GET_ALL_NEW_EMAIL:
      return { ok: true, emails: [] };
    case OPCODES.EmailCmd.SEND_PERSONAL_EMAIL:
      return { ok: true };
    case OPCODES.EmailCmd.DELETE_EMAILS:
      return { ok: true };
    case OPCODES.EmailCmd.TAKE_EMAIL_ADDITION:
      return { ok: true, rewards: [] };
    default:
      return null;
  }
}

// ── Gym (Entraînement) ────────────────────────────────────────────────────────
async function handleGym(player, cmd, data) {
  switch (cmd) {
    case OPCODES.GymCmd.DO_GYM: {
      const np = (player.perso?.puissance || 0) + 50;
      await supabase.from('personnages').update({ puissance: np })
        .eq('compte_id', player.accountId);
      if (player.perso) player.perso.puissance = np;
      return { ok: true, puissance: np };
    }
    case OPCODES.GymCmd.GET_USERGYMVO:
      return { ok: true, gymData: {} };
    default:
      return null;
  }
}

// ── Divine (Expédition) ───────────────────────────────────────────────────────
async function handleDivine(player, cmd, data) {
  switch (cmd) {
    case OPCODES.DivineCmd.QUERY_USER_DIVINE:
      return { ok: true, divineData: {} };
    case OPCODES.DivineCmd.DIVINE:
      return { ok: true, rewards: [] };
    case OPCODES.DivineCmd.FINISH:
      return { ok: true };
    default:
      return null;
  }
}

// ── Market (Marché joueurs) ───────────────────────────────────────────────────
async function handleMarket(player, cmd, data) {
  switch (cmd) {
    case OPCODES.MarketCmd.PAGE_MARKET_SELL:
      return { ok: true, items: [] };
    case OPCODES.MarketCmd.SELL_ITEM:
      return { ok: true };
    case OPCODES.MarketCmd.BUY:
      return { ok: true };
    case OPCODES.MarketCmd.CANCEL_SELL:
      return { ok: true };
    default:
      return null;
  }
}

// ── Multifuben (Donjons multijoueur) ─────────────────────────────────────────
async function handleMultifuben(player, cmd, data) {
  switch (cmd) {
    case OPCODES.MultifubenCmd.GET_MY_TEAM_INFO:
      return { ok: true, team: null };
    case OPCODES.MultifubenCmd.CREATE_TEAM:
      return { ok: true, teamId: `team_${player.id}_${Date.now()}` };
    case OPCODES.MultifubenCmd.JOIN_TEAM:
      return { ok: true };
    case OPCODES.MultifubenCmd.LEFT_TEAM:
      return { ok: true };
    case OPCODES.MultifubenCmd.START_FUBEN:
      return { ok: true };
    default:
      return null;
  }
}

// ─── ROUTEUR PRINCIPAL ────────────────────────────────────────────────────────
const handlers = {
  [DEST.USER_INFO]  : handleUserInfo,
  [DEST.CHAT]       : handleChat,
  [DEST.SCENE]      : handleScene,
  [DEST.TASK]       : handleTask,
  [DEST.EQUIP]      : handleEquip,
  [DEST.USER_ITEM]  : handleUserItem,
  [DEST.FRIEND]     : handleFriend,
  [DEST.ALLIANCE]   : handleAlliance,
  [DEST.FUBEN]      : handleFuben,
  [DEST.FIGHT]      : handleFight,
  [DEST.ARENA]      : handleArena,
  [DEST.TOWER]      : handleTower,
  [DEST.MALL]       : handleMall,
  [DEST.GIFT]       : handleGift,
  [DEST.VIP]        : handleVip,
  [DEST.RANK]       : handleRank,
  [DEST.EMAIL]      : handleEmail,
  [DEST.MARKET]     : handleMarket,
  [DEST.MULTIFUBEN] : handleMultifuben,
  21                : handleGym,
  20                : handleDivine,
};

async function routePacket(player, dest, cmd, data) {
  const handler = handlers[dest];
  if (!handler) {
    console.log(`[ROUTE] dest=${dest} cmd=${cmd} — pas de handler`);
    return;
  }
  try {
    const result = await handler(player, cmd, data);
    if (result) sendTo(player, dest, cmd, result);
  } catch(err) {
    console.error(`[ERREUR] dest=${dest} cmd=${cmd}:`, err.message);
    sendTo(player, dest, cmd, { ok: false, error: err.message });
  }
}

// ─── UTILITAIRES GAMEPLAY ─────────────────────────────────────────────────────
function generateMonsters(areaId) {
  return [
    { id: 1, nom: 'Esprit Sauvage', hp: 500, hpMax: 500, atk: 100 },
    { id: 2, nom: 'Golem de Pierre', hp: 800, hpMax: 800, atk: 150 },
  ];
}

function calcFubenCombat(perso, data) {
  const atk       = (perso?.puissance || 1000) + Math.floor(Math.random() * 200);
  const monsterId = data.monsterId || 1;
  const monsterHp = 500 + monsterId * 100;
  const victoire  = atk > monsterHp * 0.5;
  const xpGagne   = victoire ? 120 + monsterId * 20 : 0;
  const orGagne   = victoire ? 80  + monsterId * 10 : 0;
  return { victoire, xpGagne, orGagne, monsterId, dmgDealt: atk };
}

function calcPvP(attacker, defender) {
  const atkPwr = (attacker?.puissance || 1000) + Math.floor(Math.random() * 500);
  const defPwr = (defender?.puissance || 1000) + Math.floor(Math.random() * 500);
  const victoire = atkPwr >= defPwr;
  return {
    victoire,
    atkNom   : attacker?.nom,
    defNom   : defender?.nom,
    atkPwr, defPwr,
    rewardGloire: victoire ? 50 : 10,
  };
}

// ─── UTILITAIRE : déconnexion propre d'un joueur ─────────────────────────────
function disconnectPlayer(id, player) {
  console.log(`[-] Joueur #${id} déconnecté (${player.perso?.nom || '?'})`);
  if (player.sceneId) {
    const set = scenes.get(player.sceneId);
    if (set) set.delete(id);
    broadcastScene(player.sceneId, DEST.SCENE, OPCODES.SceneCmd.PUSH_LEFT_SENCE, { playerId: id });
  }
  players.delete(id);
}

// ─── UTILITAIRE : traitement d'un chunk de données (TCP ou WS binary) ────────
function processChunk(player, chunk) {
  player.buffer = Buffer.concat([player.buffer, chunk]);
  let pkt;
  while ((pkt = parsePacket(player.buffer)) !== null) {
    player.buffer = player.buffer.slice(pkt.consumed);
    const parsed = parsePayload(pkt.payload);
    if (parsed) {
      routePacket(player, parsed.dest, parsed.cmd, parsed.data);
    } else {
      // Fallback JSON brut (utilisé par le frontend WebSocket)
      try {
        const json = JSON.parse(pkt.payload.toString('utf8').replace(/\0/g,'').trim());
        if (json.dest !== undefined && json.cmd !== undefined) {
          routePacket(player, json.dest, json.cmd, json.data || {});
        }
      } catch(e) { /* paquet non reconnu */ }
    }
  }
}

// ─── SERVEUR TCP (clients Flash natifs) ──────────────────────────────────────
const tcpServer = net.createServer(socket => {
  const id     = nextId++;
  const player = { id, socket, accountId: null, perso: null, sceneId: null, x: 0, y: 0, buffer: Buffer.alloc(0), transport: 'tcp' };
  players.set(id, player);
  console.log(`[TCP+] Joueur #${id} — ${socket.remoteAddress}:${socket.remotePort}`);

  sendTo(player, DEST.USER_INFO, OPCODES.UserInfoCmd.CONNECT_OK, { serverTime: Date.now() });

  socket.on('data',  chunk => processChunk(player, chunk));
  socket.on('close', ()    => disconnectPlayer(id, player));
  socket.on('error', err   => { if (err.code !== 'ECONNRESET') console.error(`[TCP ERR] #${id}: ${err.message}`); });
});

tcpServer.on('error', err => console.error('[TCP SERVER ERR]', err.message));
tcpServer.listen(PORT, '0.0.0.0', () => console.log(`[TCP] Écoute sur port ${PORT}`));

// ─── SERVEUR HTTP + WebSocket (frontend React / Render) ──────────────────────
const http = require('http');
const { WebSocketServer } = require('ws');

const HTTP_PORT = parseInt(process.env.PORT || '10000');
const WS_PATH   = '/ws';

const httpServer = http.createServer((req, res) => {
  // CORS pour Vercel
  res.setHeader('Access-Control-Allow-Origin', '*');

  if (req.url === '/health' || req.url === '/') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status : 'online',
      name   : 'Elf&Démon : Éternal War — Game Server',
      players: players.size,
      uptime : process.uptime(),
      tcp    : PORT,
      ws     : `ws://<host>:${HTTP_PORT}${WS_PATH}`,
      opcodes: 1833,
    }));
  } else {
    res.writeHead(404);
    res.end('Not found');
  }
});

const wss = new WebSocketServer({ server: httpServer, path: WS_PATH });

wss.on('connection', (ws, req) => {
  const id = nextId++;

  // On crée un objet "socket" factice compatible avec sendTo / buildPacket
  // sendTo fait player.socket.write(buffer) → on transforme en ws.send(buffer)
  const fakeSocket = {
    write: (buf) => {
      if (ws.readyState === ws.OPEN) {
        ws.send(buf);          // envoi binaire
      }
    },
    remoteAddress: req.socket.remoteAddress,
    remotePort:    req.socket.remotePort,
  };

  const player = {
    id, socket: fakeSocket,
    accountId: null, perso: null,
    sceneId: null, x: 0, y: 0,
    buffer: Buffer.alloc(0),
    transport: 'ws',
  };
  players.set(id, player);
  console.log(`[WS+]  Joueur #${id} — ${req.socket.remoteAddress}`);

  sendTo(player, DEST.USER_INFO, OPCODES.UserInfoCmd.CONNECT_OK, { serverTime: Date.now() });

  ws.on('message', (data, isBinary) => {
    // Le frontend peut envoyer :
    //   • Buffer binaire (protocole my9yu natif)
    //   • Texte JSON  { dest, cmd, data }  (mode simplifié React)
    if (!isBinary && typeof data === 'string') {
      try {
        const json = JSON.parse(data);
        if (json.dest !== undefined && json.cmd !== undefined) {
          routePacket(player, json.dest, json.cmd, json.data || {});
        }
      } catch(e) { console.warn(`[WS] JSON invalide #${id}`); }
      return;
    }
    // Binaire → même pipeline que TCP
    const chunk = Buffer.isBuffer(data) ? data : Buffer.from(data);
    processChunk(player, chunk);
  });

  ws.on('close', () => disconnectPlayer(id, player));
  ws.on('error', err => console.error(`[WS ERR] #${id}: ${err.message}`));
});

httpServer.listen(HTTP_PORT, '0.0.0.0', () => {
  console.log(`
╔══════════════════════════════════════════════════════╗
║     Elf&Démon : Éternal War — Game Server           ║
║                                                      ║
║  TCP  (Flash natif) : 0.0.0.0:${PORT}                  ║
║  HTTP (health)      : 0.0.0.0:${HTTP_PORT}               ║
║  WS   (React)       : ws://…:${HTTP_PORT}${WS_PATH}          ║
║  Opcodes            : 1833 (148 classes AS3)         ║
╚══════════════════════════════════════════════════════╝
  `);
});

module.exports = { tcpServer, httpServer, wss, players, OPCODES, DEST };
